#!/usr/bin/env python3
"""
MISSION BRIEF — S-RANK
past.El noir Records | April 11-24, 2026
Generated by Claude — Lead Architect, Label OS
"""

from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch
from reportlab.lib.colors import HexColor, white, black
from reportlab.pdfgen import canvas
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import Paragraph
from reportlab.lib.enums import TA_LEFT, TA_CENTER

W, H = letter

# Colors
DEEP_BLACK = HexColor('#0A0A0A')
NOIR_GREEN = HexColor('#1A3A2A')
DARK_GREEN = HexColor('#0D2818')
EMERALD = HexColor('#2D6A4F')
GOLD = HexColor('#D4A843')
WARM_GOLD = HexColor('#C49A3C')
SOFT_WHITE = HexColor('#E8E0D0')
MUTED_WHITE = HexColor('#B8B0A0')
FAINT_LINE = HexColor('#2A2A2A')
RED_ALERT = HexColor('#8B2500')

def draw_bg(c, color=DEEP_BLACK):
    c.setFillColor(color)
    c.rect(0, 0, W, H, fill=1, stroke=0)

def draw_border(c):
    c.setStrokeColor(GOLD)
    c.setLineWidth(1.5)
    margin = 0.5 * inch
    c.rect(margin, margin, W - 2*margin, H - 2*margin, fill=0, stroke=1)
    # Inner border
    c.setStrokeColor(HexColor('#3A3020'))
    c.setLineWidth(0.5)
    inner = 0.6 * inch
    c.rect(inner, inner, W - 2*inner, H - 2*inner, fill=0, stroke=1)

def draw_gold_rule(c, y, x_start=1*inch, x_end=None):
    if x_end is None:
        x_end = W - 1*inch
    c.setStrokeColor(WARM_GOLD)
    c.setLineWidth(0.75)
    c.line(x_start, y, x_end, y)

def draw_faint_rule(c, y):
    c.setStrokeColor(FAINT_LINE)
    c.setLineWidth(0.5)
    c.line(1*inch, y, W - 1*inch, y)

def draw_text(c, text, x, y, font="Helvetica", size=10, color=SOFT_WHITE):
    c.setFont(font, size)
    c.setFillColor(color)
    c.drawString(x, y, text)

def draw_centered(c, text, y, font="Helvetica", size=10, color=SOFT_WHITE):
    c.setFont(font, size)
    c.setFillColor(color)
    tw = c.stringWidth(text, font, size)
    c.drawString((W - tw) / 2, y, text)

def draw_right(c, text, y, font="Helvetica", size=10, color=SOFT_WHITE):
    c.setFont(font, size)
    c.setFillColor(color)
    tw = c.stringWidth(text, font, size)
    c.drawString(W - 1*inch - tw, y, text)

def wrapped_text(c, text, x, y, max_width, font="Helvetica", size=10, color=SOFT_WHITE, leading=14):
    """Draw text with word wrapping. Returns the y position after the last line."""
    c.setFont(font, size)
    c.setFillColor(color)
    words = text.split()
    lines = []
    current_line = ""
    for word in words:
        test = current_line + (" " if current_line else "") + word
        if c.stringWidth(test, font, size) <= max_width:
            current_line = test
        else:
            if current_line:
                lines.append(current_line)
            current_line = word
    if current_line:
        lines.append(current_line)

    for line in lines:
        c.drawString(x, y, line)
        y -= leading
    return y

# ============================================================
# BUILD THE PDF
# ============================================================

output_path = "/sessions/tender-focused-ptolemy/mnt/Ethan Payton Label OS/MISSION_BRIEF_APR11.pdf"
c = canvas.Canvas(output_path, pagesize=letter)

# ============================================================
# PAGE 1: COVER
# ============================================================
draw_bg(c, DEEP_BLACK)

# Subtle noir gradient strip at top
c.setFillColor(NOIR_GREEN)
c.rect(0, H - 2.5*inch, W, 2.5*inch, fill=1, stroke=0)
# Fade back to black
for i in range(20):
    alpha_color = HexColor('#0A0A0A')
    c.setFillColor(alpha_color)
    c.setFillAlpha(i / 20.0)
    c.rect(0, H - 2.5*inch - i*3, W, 3, fill=1, stroke=0)
c.setFillAlpha(1)

draw_border(c)

# Classification header
draw_centered(c, "CLASSIFIED  //  S-RANK  //  EYES ONLY", H - 1.2*inch, "Helvetica-Bold", 8, GOLD)
draw_gold_rule(c, H - 1.35*inch)

# Title block
draw_centered(c, "MISSION BRIEF", H - 2.1*inch, "Helvetica-Bold", 36, GOLD)
draw_centered(c, "CODENAME: ALL LOVE", H - 2.5*inch, "Helvetica", 16, SOFT_WHITE)

draw_gold_rule(c, H - 2.75*inch)

# Mission parameters
y = H - 3.3*inch
params = [
    ("OPERATIVE", "Ethan Payton  /  past.El"),
    ("LABEL", "past.El noir Records"),
    ("DISTRIBUTOR", "Amuse Pro"),
    ("CLASSIFICATION", "S-Rank  //  Solo Execution"),
    ("WINDOW", "April 11 \u2014 April 24, 2026"),
    ("DAYS REMAINING", "13"),
]

for label, value in params:
    draw_text(c, label, 1.2*inch, y, "Helvetica-Bold", 8, MUTED_WHITE)
    draw_text(c, value, 3.2*inch, y, "Helvetica", 11, SOFT_WHITE)
    y -= 22

draw_gold_rule(c, y - 5)

# Objective
y -= 35
draw_text(c, "PRIMARY OBJECTIVE", 1.2*inch, y, "Helvetica-Bold", 12, GOLD)
y -= 22
y = wrapped_text(c, "Master and upload as many of the 5 remaining tracks as possible. Ship each one the hour it locks. Collect all on April 24 as the ALL LOVE EP.", 1.2*inch, y, W - 2.4*inch, "Helvetica", 11, SOFT_WHITE, 16)

y -= 20
draw_text(c, "SUCCESS CONDITION", 1.2*inch, y, "Helvetica-Bold", 12, GOLD)
y -= 22
y = wrapped_text(c, "More tracks mastered and uploaded on April 24 than exist today. Today: 1 live (SEE ME). Target: 6.", 1.2*inch, y, W - 2.4*inch, "Helvetica", 11, SOFT_WHITE, 16)

# Footer
draw_gold_rule(c, 1.2*inch)
draw_centered(c, "past.El noir Records  //  Label OS  //  April 2026", 0.95*inch, "Helvetica", 7, MUTED_WHITE)
draw_centered(c, "\"The system works the same at every zoom level.\"", 0.75*inch, "Helvetica-Oblique", 8, WARM_GOLD)

c.showPage()

# ============================================================
# PAGE 2: THE TARGETS
# ============================================================
draw_bg(c)
draw_border(c)

draw_centered(c, "TARGET MANIFEST", H - 1.2*inch, "Helvetica-Bold", 20, GOLD)
draw_gold_rule(c, H - 1.4*inch)

draw_centered(c, "6 TRACKS  //  1 LIVE  //  5 REMAINING  //  ~50 HOURS OF WORK", H - 1.7*inch, "Helvetica", 9, MUTED_WHITE)

# Track cards
tracks = [
    {"name": "SEE ME", "status": "LIVE", "date": "Mar 13", "hours": "0", "color": EMERALD, "note": "Shipped. On Spotify. The proof it can be done."},
    {"name": "SWEET FRUSTRATION", "status": "IN PROGRESS", "date": "---", "hours": "~10", "color": WARM_GOLD, "note": "Mix26 bounced Apr 8. Closest to done. Goes first."},
    {"name": "EAST SIDE LOVE", "status": "IN PROGRESS", "date": "---", "hours": "~10", "color": WARM_GOLD, "note": "Multiple bounces Apr 8 (25_5 series). Active mixing."},
    {"name": "WANT U 2", "status": "PENDING", "date": "---", "hours": "~10", "color": MUTED_WHITE, "note": "Recording + mixing + mastering remaining."},
    {"name": "LIKE I DID", "status": "PENDING", "date": "---", "hours": "~10", "color": MUTED_WHITE, "note": "Recording + mixing + mastering remaining."},
    {"name": "GREEN LIGHTS", "status": "PENDING", "date": "---", "hours": "~10", "color": MUTED_WHITE, "note": "Recording + mixing + mastering remaining."},
]

y = H - 2.2*inch
for t in tracks:
    # Track card background
    card_h = 52
    c.setFillColor(HexColor('#141414'))
    c.roundRect(1*inch, y - card_h + 15, W - 2*inch, card_h, 4, fill=1, stroke=0)

    # Status indicator bar
    c.setFillColor(t["color"])
    c.roundRect(1*inch, y - card_h + 15, 4, card_h, 2, fill=1, stroke=0)

    # Track name
    draw_text(c, t["name"], 1.3*inch, y, "Helvetica-Bold", 13, t["color"])

    # Status badge
    draw_right(c, t["status"], y, "Helvetica-Bold", 9, t["color"])

    # Details line
    draw_text(c, t["note"], 1.3*inch, y - 16, "Helvetica", 8, MUTED_WHITE)

    # Hours remaining
    draw_text(c, f"Hours remaining: {t['hours']}", 1.3*inch, y - 30, "Helvetica", 8, HexColor('#666666'))

    y -= card_h + 8

# Math box
y -= 15
c.setFillColor(HexColor('#1A1A10'))
c.setStrokeColor(WARM_GOLD)
c.setLineWidth(0.5)
c.roundRect(1*inch, y - 70, W - 2*inch, 70, 4, fill=1, stroke=1)

draw_text(c, "THE MATH", 1.3*inch, y - 15, "Helvetica-Bold", 10, GOLD)
draw_text(c, "50 hours of work  /  13 days  =  ~4 hrs/day studio time", 1.3*inch, y - 32, "Helvetica", 10, SOFT_WHITE)
draw_text(c, "DoorDash 6:30\u20139 AM  +  4 hrs studio  =  done by 2 PM most days.", 1.3*inch, y - 48, "Helvetica", 10, SOFT_WHITE)
draw_text(c, "Amuse Pro: 48hr review. Upload the hour a master locks. No batching.", 1.3*inch, y - 64, "Helvetica", 9, MUTED_WHITE)

# Footer
draw_gold_rule(c, 1.2*inch)
draw_centered(c, "Closest to done goes first. Intuition guides the sequence.", 0.9*inch, "Helvetica-Oblique", 8, WARM_GOLD)

c.showPage()

# ============================================================
# PAGE 3: DAILY STRUCTURE
# ============================================================
draw_bg(c)
draw_border(c)

draw_centered(c, "DAILY OPERATING STRUCTURE", H - 1.2*inch, "Helvetica-Bold", 20, GOLD)
draw_gold_rule(c, H - 1.4*inch)
draw_centered(c, "SINGLE-MODE DAYS  //  NO MULTITASKING  //  NO PLANNING", H - 1.7*inch, "Helvetica", 9, MUTED_WHITE)

y = H - 2.2*inch

# Morning block
c.setFillColor(HexColor('#141414'))
c.roundRect(1*inch, y - 95, W - 2*inch, 95, 4, fill=1, stroke=0)
c.setFillColor(EMERALD)
c.roundRect(1*inch, y - 95, 4, 95, 2, fill=1, stroke=0)

draw_text(c, "MORNING BLOCK", 1.3*inch, y - 12, "Helvetica-Bold", 12, EMERALD)
draw_text(c, "Wake", 1.3*inch, y - 32, "Helvetica-Bold", 9, MUTED_WHITE)
draw_text(c, "32oz water + sea salt. Jnana Mudra + OM, 60 seconds.", 2.5*inch, y - 32, "Helvetica", 9, SOFT_WHITE)
draw_text(c, "6:00 AM", 1.3*inch, y - 50, "Helvetica-Bold", 9, MUTED_WHITE)
draw_text(c, "Protein meal (eggs + banana, prepped night before).", 2.5*inch, y - 50, "Helvetica", 9, SOFT_WHITE)
draw_text(c, "6:30 AM", 1.3*inch, y - 68, "Helvetica-Bold", 9, MUTED_WHITE)
draw_text(c, "DoorDash. Morning surge. Stop at 9 AM.", 2.5*inch, y - 68, "Helvetica", 9, SOFT_WHITE)
draw_text(c, "9:00 AM", 1.3*inch, y - 86, "Helvetica-Bold", 9, MUTED_WHITE)
draw_text(c, "Wheels down. Home. Refuel if needed.", 2.5*inch, y - 86, "Helvetica", 9, SOFT_WHITE)

y -= 115

# Studio block
c.setFillColor(HexColor('#141414'))
c.roundRect(1*inch, y - 130, W - 2*inch, 130, 4, fill=1, stroke=0)
c.setFillColor(GOLD)
c.roundRect(1*inch, y - 130, 4, 130, 2, fill=1, stroke=0)

draw_text(c, "STUDIO BLOCK", 1.3*inch, y - 12, "Helvetica-Bold", 12, GOLD)
draw_text(c, "9:30 AM", 1.3*inch, y - 35, "Helvetica-Bold", 9, MUTED_WHITE)
draw_text(c, "S3 Check-in: \"Name your mental state before opening the DAW.\"", 2.5*inch, y - 35, "Helvetica", 9, SOFT_WHITE)
draw_text(c, "Rate 1\u201310. No judgment. 30 seconds. Then open the project.", 2.5*inch, y - 50, "Helvetica", 9, MUTED_WHITE)
draw_text(c, "9:35 AM", 1.3*inch, y - 70, "Helvetica-Bold", 9, MUTED_WHITE)
draw_text(c, "DAW open. One track. Work until it's done or you hit a wall.", 2.5*inch, y - 70, "Helvetica", 9, SOFT_WHITE)
draw_text(c, "RULE", 1.3*inch, y - 92, "Helvetica-Bold", 9, RED_ALERT)
draw_text(c, "Do not bounce the same track more than 3 times in one sitting.", 2.5*inch, y - 92, "Helvetica", 9, SOFT_WHITE)
draw_text(c, "If stuck after 3 bounces, switch to the next closest track.", 2.5*inch, y - 107, "Helvetica", 9, MUTED_WHITE)
draw_text(c, "No session runs past 8:30 PM. Lights out 10:30.", 2.5*inch, y - 122, "Helvetica", 9, MUTED_WHITE)

y -= 150

# On master lock
c.setFillColor(HexColor('#1A1A10'))
c.setStrokeColor(WARM_GOLD)
c.setLineWidth(0.5)
c.roundRect(1*inch, y - 100, W - 2*inch, 100, 4, fill=1, stroke=1)

draw_text(c, "ON MASTER LOCK (same hour)", 1.3*inch, y - 15, "Helvetica-Bold", 11, GOLD)

steps = [
    "1.  Bounce final master.",
    "2.  Create cover art (or use EP template). ~30 min.",
    "3.  Upload to Amuse. Submit.",
    "4.  Open Spotify for Artists. Submit editorial pitch.",
    "5.  Close the project file. Do not reopen. Move to next track.",
]
sy = y - 35
for step in steps:
    draw_text(c, step, 1.5*inch, sy, "Helvetica", 9, SOFT_WHITE)
    sy -= 14

y -= 120

# Evening
c.setFillColor(HexColor('#141414'))
c.roundRect(1*inch, y - 55, W - 2*inch, 55, 4, fill=1, stroke=0)
c.setFillColor(HexColor('#4A3A6A'))
c.roundRect(1*inch, y - 55, 4, 55, 2, fill=1, stroke=0)

draw_text(c, "EVENING", 1.3*inch, y - 12, "Helvetica-Bold", 12, HexColor('#8A7AAA'))
draw_text(c, "8:30 PM", 1.3*inch, y - 32, "Helvetica-Bold", 9, MUTED_WHITE)
draw_text(c, "Wheels down. No screens after 9:30. Mullein tea. Prep tomorrow's protein.", 2.5*inch, y - 32, "Helvetica", 9, SOFT_WHITE)
draw_text(c, "10:30 PM", 1.3*inch, y - 48, "Helvetica-Bold", 9, MUTED_WHITE)
draw_text(c, "Lights out. Non-negotiable.", 2.5*inch, y - 48, "Helvetica", 9, SOFT_WHITE)

# Footer
draw_gold_rule(c, 1.2*inch)
draw_centered(c, "One track per session. Closest to done goes first.", 0.9*inch, "Helvetica-Oblique", 8, WARM_GOLD)

c.showPage()

# ============================================================
# PAGE 4: DO NOT / ABORT CONDITIONS
# ============================================================
draw_bg(c)
draw_border(c)

draw_centered(c, "MISSION CONSTRAINTS", H - 1.2*inch, "Helvetica-Bold", 20, GOLD)
draw_gold_rule(c, H - 1.4*inch)

y = H - 1.9*inch

# DO NOT block
c.setFillColor(HexColor('#1A0A0A'))
c.setStrokeColor(RED_ALERT)
c.setLineWidth(1)
c.roundRect(1*inch, y - 195, W - 2*inch, 195, 4, fill=1, stroke=1)

draw_text(c, "DO NOT", 1.3*inch, y - 15, "Helvetica-Bold", 14, RED_ALERT)

donots = [
    "Open Claude unless a track is stuck on a specific technical problem.",
    "Build, plan, or organize anything. The plan exists. Execute it.",
    "Create content. No posts, no captions, no Canvas loops. Not yet.",
    "Bounce the same track more than 3 times in one sitting.",
    "Start anything not on the 6-track list.",
    "Reopen a finished/uploaded project file.",
    "Check streaming numbers, follower counts, or analytics.",
    "Adjust the system. No Oracle tweaks, no tool updates, no refactors.",
    "Let \"I should fix the plan\" replace \"I should open the DAW.\"",
    "Skip protein before a session. Executive function crashes at hour 3.",
]

sy = y - 38
for i, item in enumerate(donots):
    draw_text(c, f"\u2718", 1.3*inch, sy, "Helvetica-Bold", 10, RED_ALERT)
    draw_text(c, item, 1.6*inch, sy, "Helvetica", 9, SOFT_WHITE)
    sy -= 16

y -= 220

# REMEMBER block
c.setFillColor(HexColor('#0A1A0A'))
c.setStrokeColor(EMERALD)
c.setLineWidth(1)
c.roundRect(1*inch, y - 155, W - 2*inch, 155, 4, fill=1, stroke=1)

draw_text(c, "REMEMBER", 1.3*inch, y - 15, "Helvetica-Bold", 14, EMERALD)

remembers = [
    "You already shipped SEE ME. You know how to do this.",
    "The masters weren't done \u2014 that's why the plan slipped. Not laziness.",
    "Amuse Pro = 48 hours. Upload the hour it locks. Don't wait.",
    "Day 9 sober. Executive function is low. That's neurochemistry, not weakness.",
    "Ignition structures carry you: water, mudra, protein, DAW open.",
    "Checkboxes are victories. Each upload is a dopamine hit that's EARNED.",
    "The sequence doesn't matter until they're all done. Let Cyanite sort it.",
    "April 24 is math, not pressure. Ship what's ready. EP collects it all.",
]

sy = y - 38
for item in remembers:
    draw_text(c, "\u2714", 1.3*inch, sy, "Helvetica-Bold", 10, EMERALD)
    draw_text(c, item, 1.6*inch, sy, "Helvetica", 9, SOFT_WHITE)
    sy -= 15

# Footer
draw_gold_rule(c, 1.2*inch)
draw_centered(c, "\"Builder-avoidance loops are neurochemical, not laziness.\"", 0.95*inch, "Helvetica-Oblique", 8, WARM_GOLD)
draw_centered(c, "When the urge to fix the system hits, open the DAW instead.", 0.75*inch, "Helvetica-Oblique", 8, MUTED_WHITE)

c.showPage()

# ============================================================
# PAGE 5: SOBRIETY + CLOSING
# ============================================================
draw_bg(c)
draw_border(c)

draw_centered(c, "THE CLOCK", H - 1.2*inch, "Helvetica-Bold", 20, GOLD)
draw_gold_rule(c, H - 1.4*inch)

y = H - 1.9*inch

# Sobriety counter
c.setFillColor(HexColor('#141414'))
c.roundRect(1*inch, y - 80, W - 2*inch, 80, 4, fill=1, stroke=0)

draw_centered(c, "SOBRIETY", y - 15, "Helvetica-Bold", 10, MUTED_WHITE)
draw_centered(c, "DAY 9", y - 42, "Helvetica-Bold", 28, GOLD)
draw_centered(c, "April 2, 2026 \u2192 Present  //  Detox Window (Days 1\u201328)  //  Executive Function LOW", y - 65, "Helvetica", 8, MUTED_WHITE)

y -= 105

# The detox truth
c.setFillColor(HexColor('#141414'))
c.roundRect(1*inch, y - 85, W - 2*inch, 85, 4, fill=1, stroke=0)

draw_text(c, "THE DETOX TRUTH", 1.3*inch, y - 15, "Helvetica-Bold", 11, GOLD)
ty = y - 35
ty = wrapped_text(c, "You are in the hardest window. Days 1-28 is when the brain screams loudest for the old patterns. Every session you sit through, every bounce you export, every upload you complete is a victory against neurochemistry that is actively working against you.", 1.3*inch, ty, W - 2.6*inch, "Helvetica", 9, SOFT_WHITE, 14)
ty -= 6
ty = wrapped_text(c, "The ignition structures exist because willpower doesn't work here. Water, mudra, protein, DAW open. That sequence IS the discipline. Trust it.", 1.3*inch, ty, W - 2.6*inch, "Helvetica", 9, MUTED_WHITE, 14)

y -= 110

# By April 24 box
c.setFillColor(HexColor('#1A1A10'))
c.setStrokeColor(WARM_GOLD)
c.setLineWidth(1)
c.roundRect(1*inch, y - 100, W - 2*inch, 100, 4, fill=1, stroke=1)

draw_text(c, "BY APRIL 24, YOU WILL HAVE:", 1.3*inch, y - 18, "Helvetica-Bold", 11, GOLD)
outcomes = [
    "A 6-track EP on Spotify, Apple Music, and every major platform.",
    "Proof that you can ship a body of work solo, sober, with no label.",
    "Sobriety Day 22. Past the worst of detox. Clarity arriving.",
    "A catalog that proves to Summerfest 2027 bookers you're real.",
    "The foundation for CREAM (Phase 2) built on proven execution.",
]
oy = y - 40
for item in outcomes:
    draw_text(c, "\u25C6", 1.3*inch, oy, "Helvetica", 8, GOLD)
    draw_text(c, item, 1.55*inch, oy, "Helvetica", 9, SOFT_WHITE)
    oy -= 14

y -= 125

# Closing quote
draw_gold_rule(c, y)
y -= 30

draw_centered(c, "You are not choosing between war mode and sustainability.", y, "Helvetica-Oblique", 11, WARM_GOLD)
y -= 18
draw_centered(c, "You are running a phased campaign.", y, "Helvetica-Oblique", 11, WARM_GOLD)
y -= 30
draw_centered(c, "The sprint IS the strategy.", y, "Helvetica-Bold", 14, GOLD)

y -= 40
draw_gold_rule(c, y)

y -= 25
draw_centered(c, "Close this document. Open the DAW.", y, "Helvetica-Bold", 12, SOFT_WHITE)

# Footer
draw_gold_rule(c, 1.2*inch)
draw_centered(c, "past.El noir Records  //  Sovereign Action Plan  //  S-Rank Mission", 0.95*inch, "Helvetica", 7, MUTED_WHITE)
draw_centered(c, "Distributor: Amuse. Always has been.", 0.75*inch, "Helvetica", 7, MUTED_WHITE)

c.showPage()
c.save()
print(f"Mission brief saved to: {output_path}")
