// ═══════════════════════════════════════════════════════════════
// lib/phaseMap.ts — Sovereign Scroll × Oracle Compass
// Full 91-day PHASE_MAP — source of truth for TodayPlan component
//
// APR 27 WATERFALL PIVOT:
//   Phase 1a: Production Sprint (Apr 27 → May 1)
//   Phase 1b: ESL Campaign (May 2 → May 22) — Single #1 drops May 9
//   Phase 1c: GL Campaign (May 16 → Jun 5) — Single #2 drops May 23
//   Phase 1d: SF Campaign (May 30 → Jun 19) — Single #3 drops Jun 6
//   Phase 1e: EP Drop (Jun 13 → Jun 27) — ALL LOVE EP drops Jun 20
//   Phase 2: Compound (Jun 28 → Jul 17) — Sync, live, CREAM decision
// ═══════════════════════════════════════════════════════════════

export interface PhaseDay {
  arc: string;
  phase: string;
  weekName: string;
  dayLabel: string;
  badge: string;
  badgeClass: string;
  cardClass: string;
  deliverable: string;
  sub: string;
  nn: string[];
  dropLabel?: string;
  dropDate?: string;
  warning?: {
    type: string;
    icon: string;
    text: string;
  };
}

// ═══ NON-NEGOTIABLE TEMPLATES ═══
const ARC1_NN = [
  "DoorDash 6:30–9 AM ($60 target)",
  "Calisthenics + mudras (30 min)",
  "Tomorrow's first task on paper before bed",
];
const FLATLINE_NN = [
  "Calisthenics — even if pointless",
  "Meditation / mudras — keep the slot",
  "One content piece max (ceiling, not floor)",
];
const ARC2_NN = [
  "DoorDash block",
  "Calisthenics + meditation",
  "One primary creative deliverable",
];
const ARC3_NN = [
  "DoorDash + calisthenics",
  "One creative + one business deliverable",
  "Phone away after 10 PM",
];

export const PHASE_MAP: Record<string, PhaseDay> = {
  // ═══ ARC 1 — WEEK 1: SHIP THE EP ═══
  "2026-04-18": { arc: "1", phase: "Honeymoon", weekName: "Wk 1 — Ship the EP", dayLabel: "COMP DAY", badge: "Comp", badgeClass: "badge-gold", cardClass: "card-left", deliverable: "Comp all 4 tracks · ESL → SF → WU2 → RV", sub: "9:30 AM – 6 PM · 2 hrs/track + 30 min tuning buffer · Reference SEE ME", nn: ARC1_NN, dropLabel: "Days to EP", dropDate: "2026-04-24" },
  "2026-04-19": { arc: "1", phase: "Honeymoon", weekName: "Wk 1 — Ship the EP", dayLabel: "MIX DAY", badge: "Mix", badgeClass: "badge-blue", cardClass: "card-left blue", deliverable: "Mix all 4 tracks · 9-stage Sovereign Protocol", sub: "10 AM – 1 AM · 3 hrs/track · QC pass + phone/car listen", nn: ARC1_NN, dropLabel: "Days to EP", dropDate: "2026-04-24" },
  "2026-04-20": { arc: "1", phase: "Honeymoon", weekName: "Wk 1 — Ship the EP", dayLabel: "MASTER + UPLOAD", badge: "Upload", badgeClass: "badge-green", cardClass: "card-left green", deliverable: "Master 4 tracks · Upload to Amuse 8–10 PM", sub: "Ozone 12 · 24/44.1/-1 dBFS · Screenshot confirmation + ISRC page", warning: { type: "important", icon: "📋", text: "Open <strong>AMUSE_UPLOAD_CHECKLIST_APR20.md</strong>. Top to bottom. Screenshot every gate." }, nn: ARC1_NN, dropLabel: "Days to EP", dropDate: "2026-04-24" },
  "2026-04-21": { arc: "1", phase: "Honeymoon", weekName: "Wk 1 — Ship the EP", dayLabel: "COMPLIANCE + CONTENT BATCH", badge: "Batch", badgeClass: "badge-gold", cardClass: "card-left", deliverable: "ASCAP/BMI register all 4 + SEE ME · Batch-film 7 posts", sub: "7 AM: Amuse rejection check · One filming session, edit all week", nn: ARC1_NN, dropLabel: "Days to EP", dropDate: "2026-04-24" },
  "2026-04-22": { arc: "1", phase: "Honeymoon", weekName: "Wk 1 — Ship the EP", dayLabel: "EDITORIAL PITCHES", badge: "Pitch", badgeClass: "badge-gold", cardClass: "card-left", deliverable: "Spotify for Artists pitches (backup) · Edit + schedule Posts 1–3", sub: "Draft WU2 + RV pitches · Denver-heavy geo context", nn: ARC1_NN, dropLabel: "Days to EP", dropDate: "2026-04-24" },
  "2026-04-23": { arc: "1", phase: "Sprint — ESL Upload Night", weekName: "Wk 1 — ESL Single → EP", dayLabel: "ESL MASTER + AMUSE UPLOAD", badge: "Upload", badgeClass: "badge-green", cardClass: "card-left green", deliverable: "Lock ESL master · Cover art · Amuse upload tonight", sub: "72-hr Amuse ingestion → pre-save live Apr 26 → ESL drops May 1", warning: { type: "important", icon: "📋", text: "<strong>ESL is the single.</strong> Ship clean > miss. Screenshot ISRC page. Verify Amuse preserves ESL ISRC when it becomes track 1 of EP May 8 (waterfall)." }, nn: ARC1_NN, dropLabel: "Days to ESL", dropDate: "2026-05-01" },
  "2026-04-24": { arc: "1", phase: "Sprint — EP Production", weekName: "Wk 1 — ESL Single → EP", dayLabel: "EP TRACKS — RECORD/MIX", badge: "Produce", badgeClass: "badge-blue", cardClass: "card-left blue", deliverable: "Push SF / Green Light / WANT U 2 — record + mix toward Apr 30 upload", sub: "Masters must lock Apr 30 for May 8 EP release. 6 days, 3 tracks.", nn: ARC1_NN, dropLabel: "Days to ESL", dropDate: "2026-05-01" },

  // ═══ ARC 1 — WEEK 2: ESL LIVE + EP SPRINT ═══
  "2026-04-25": { arc: "1", phase: "Sprint — EP Production", weekName: "Wk 2 — ESL Live + EP Sprint", dayLabel: "EP SPRINT DAY 2", badge: "Produce", badgeClass: "badge-blue", cardClass: "card-left blue", deliverable: "Produce/Mix SF + Green Light + WU2", sub: "Push toward Apr 30 lock", nn: ARC1_NN, dropLabel: "Days to ESL", dropDate: "2026-05-01" },
  "2026-04-26": { arc: "1", phase: "Sprint — EP Production", weekName: "Wk 2 — ESL Live + EP Sprint", dayLabel: "EP SPRINT DAY 3", badge: "Produce", badgeClass: "badge-blue", cardClass: "card-left blue", deliverable: "Produce/Mix SF + Green Light + WU2", sub: "Sunday — keep pushing", nn: ARC1_NN, dropLabel: "Days to ESL", dropDate: "2026-05-01" },
  "2026-04-27": { arc: "1", phase: "Sprint — EP Production", weekName: "Wk 2 — ESL Live + EP Sprint", dayLabel: "CHECK AMUSE + MASTER GL", badge: "Master", badgeClass: "badge-green", cardClass: "card-left green", deliverable: "Check Amuse for ESL pre-save link · Master Green Light", sub: "ESL uploaded Apr 24 → 72hr ingestion → link should be live today. Copy link, replace [LINK] in all drafts. Then FL Studio: Green Light master.", warning: { type: "important", icon: "🔗", text: "<strong>Get the ESL Spotify link TODAY.</strong> Every DM and caption has a [LINK] placeholder. Cannot start May 1 blitz without it." }, nn: ARC1_NN, dropLabel: "Days to ESL", dropDate: "2026-05-01" },

  // ═══ PRODUCTION SPRINT (Apr 28 – May 1) ═══
  "2026-04-28": { arc: "1", phase: "Production Sprint", weekName: "Wk 2 — Record + Mix", dayLabel: "RECORD ALL VOCALS", badge: "Record", badgeClass: "badge-blue", cardClass: "card-left blue", deliverable: "4-hour vocal batch: GL + SF + WU2 toplines + extras", sub: "Batch recording — all vocals across all 3 tracks in one session. Performer mode, not engineer mode.", nn: ARC1_NN, dropLabel: "Days to ESL", dropDate: "2026-05-09" },
  "2026-04-29": { arc: "1", phase: "Production Sprint", weekName: "Wk 2 — Record + Mix", dayLabel: "MIX DAY 1", badge: "Mix", badgeClass: "badge-blue", cardClass: "card-left blue", deliverable: "Mix GL + SF with complete stems", sub: "Engineer mode. All vocal stems in hand from yesterday. 9-stage protocol.", nn: ARC1_NN, dropLabel: "Days to ESL", dropDate: "2026-05-09" },
  "2026-04-30": { arc: "1", phase: "Production Sprint", weekName: "Wk 2 — Record + Mix", dayLabel: "MIX DAY 2", badge: "Mix", badgeClass: "badge-blue", cardClass: "card-left blue", deliverable: "Mix WU2 · Begin ESL master fix", sub: "Finish WU2 mix. Pull up ESL project — identify wrong file, prep correct master.", nn: ARC1_NN, dropLabel: "Days to ESL", dropDate: "2026-05-09" },
  "2026-05-01": { arc: "1", phase: "Production Sprint", weekName: "Wk 2 — Record + Mix", dayLabel: "MASTER ESL + UPLOAD", badge: "Master", badgeClass: "badge-green", cardClass: "card-left green", deliverable: "Lock corrected ESL master · Re-upload to Amuse", sub: "Illangelo chain → QC → bounce → Amuse upload. Set release date May 9.", warning: { type: "important", icon: "📋", text: "<strong>ESL re-upload today.</strong> Fix the audio file. Amuse needs ~7 days ingestion for May 9 drop." }, nn: ARC1_NN, dropLabel: "Days to ESL", dropDate: "2026-05-09" },

  // ═══ ESL CAMPAIGN (May 2 – May 22) ═══
  "2026-05-02": { arc: "1", phase: "ESL Campaign — Pre-Release", weekName: "Wk 3 — ESL Pre-Save", dayLabel: "ESL CONTENT PREP", badge: "Content", badgeClass: "badge-gold", cardClass: "card-left", deliverable: "Write ESL captions (5 pillars) · Schedule pre-save push", sub: "7 days to drop. Every post ends: East Side Love — May 9", nn: ARC1_NN, dropLabel: "Days to ESL", dropDate: "2026-05-09" },
  "2026-05-03": { arc: "1", phase: "ESL Campaign — Pre-Release", weekName: "Wk 3 — ESL Pre-Save", dayLabel: "DM LIST BUILD", badge: "Outreach", badgeClass: "badge-gold", cardClass: "card-left", deliverable: "Build 50-person DM list · Prep God Tier + Warm + Cold tiers", sub: "Sunday. Grief journal 20 min → DM list build.", nn: FLATLINE_NN, dropLabel: "Days to ESL", dropDate: "2026-05-09" },
  "2026-05-04": { arc: "1", phase: "ESL Campaign — Pre-Release", weekName: "Wk 3 — ESL Pre-Save", dayLabel: "PRE-SAVE PUSH", badge: "Content", badgeClass: "badge-gold", cardClass: "card-left", deliverable: "Post #1: ESL teaser · IG Story with pre-save link", sub: "Check Amuse — pre-save link should be live by now.", nn: ARC1_NN, dropLabel: "Days to ESL", dropDate: "2026-05-09" },
  "2026-05-05": { arc: "1", phase: "ESL Campaign — Pre-Release", weekName: "Wk 3 — ESL Pre-Save", dayLabel: "COMPLIANCE + CONTENT", badge: "Compliance", badgeClass: "badge-purple", cardClass: "card-left purple", deliverable: "Monday: ASCAP/MLC/Songtrust for SEE ME (overdue) · Post #2", sub: "Morning compliance, afternoon content.", nn: ARC1_NN, dropLabel: "Days to ESL", dropDate: "2026-05-09" },
  "2026-05-06": { arc: "1", phase: "ESL Campaign — Pre-Release", weekName: "Wk 3 — ESL Pre-Save", dayLabel: "EDITORIAL PITCH", badge: "Pitch", badgeClass: "badge-blue", cardClass: "card-left blue", deliverable: "Spotify for Artists: ESL editorial pitch · Post #3", sub: "Pitch 7+ days before release for best editorial window.", nn: ARC1_NN, dropLabel: "Days to ESL", dropDate: "2026-05-09" },
  "2026-05-07": { arc: "1", phase: "ESL Campaign — Pre-Release", weekName: "Wk 3 — ESL Pre-Save", dayLabel: "WORLD-BUILDING POST", badge: "Content", badgeClass: "badge-gold", cardClass: "card-left", deliverable: "Post #4: Milwaukee / east side imagery · ESL story", sub: "The emotional context behind the track.", nn: ARC1_NN, dropLabel: "Days to ESL", dropDate: "2026-05-09" },
  "2026-05-08": { arc: "1", phase: "ESL Campaign — Pre-Release", weekName: "Wk 3 — ESL Pre-Save", dayLabel: "EVE OF ESL", badge: "Eve", badgeClass: "badge-orange", cardClass: "card-left orange", deliverable: "Post #5: Talk to 'Em — what ESL means to you · Final pre-save push", sub: "Tomorrow it's live. DM blitz list finalized. Ads staged.", nn: ARC1_NN, dropLabel: "ESL tomorrow", dropDate: "2026-05-09" },
  "2026-05-09": { arc: "1", phase: "ESL Release Day", weekName: "Wk 3 — ESL Drops", dayLabel: "EAST SIDE LOVE DROPS", badge: "Release", badgeClass: "badge-red", cardClass: "card-left red", deliverable: "ESL live everywhere · Release post 9 AM · DM Blitz 10 AM + 2 PM", sub: "50 DMs total. DoorDash AM block first. Wheels down 8 PM.", warning: { type: "important", icon: "🎉", text: "<strong>Single #1 is live.</strong> Release Radar trigger #1. Don't check stats after 8 PM." }, nn: ["DoorDash 6:30–9 AM", "50 DMs sent (10 AM + 2 PM)", "Do NOT check stats after 8 PM"], dropLabel: "Days to GL", dropDate: "2026-05-23" },
  "2026-05-10": { arc: "1", phase: "ESL Campaign — Post-Release", weekName: "Wk 4 — ESL Live", dayLabel: "ESL DAY 2", badge: "Momentum", badgeClass: "badge-red", cardClass: "card-left red", deliverable: "Talk to 'Em: story behind ESL · Respond to DM engagement", sub: "Saturday. Let the release breathe. One post max.", nn: FLATLINE_NN, dropLabel: "Days to GL", dropDate: "2026-05-23" },
  "2026-05-11": { arc: "1", phase: "ESL Campaign — Post-Release", weekName: "Wk 4 — ESL Live", dayLabel: "SUNDAY REVIEW", badge: "Sunday", badgeClass: "badge-purple", cardClass: "card-left purple", deliverable: "Grief journal · ESL 48-hr data check · S4A screenshots", sub: "Numbers, not feelings. Save rate check.", nn: FLATLINE_NN, dropLabel: "Days to GL", dropDate: "2026-05-23" },
  "2026-05-12": { arc: "1", phase: "ESL + GL Overlap", weekName: "Wk 4 — ESL Live + GL Master", dayLabel: "MASTER GREEN LIGHT", badge: "Master", badgeClass: "badge-green", cardClass: "card-left green", deliverable: "Master Green Light · Illangelo chain · QC", sub: "ESL is live and running. Now lock GL master for May 23 drop.", nn: ARC1_NN, dropLabel: "Days to GL", dropDate: "2026-05-23" },
  "2026-05-13": { arc: "1", phase: "ESL + GL Overlap", weekName: "Wk 4 — ESL Live + GL Master", dayLabel: "GL STEMS + ARTWORK", badge: "Export", badgeClass: "badge-green", cardClass: "card-left green", deliverable: "Export GL stems · Begin GL cover art", sub: "Master, instrumental, clean, acapella, stems. Cover art for single.", nn: ARC1_NN, dropLabel: "Days to GL", dropDate: "2026-05-23" },
  "2026-05-14": { arc: "1", phase: "ESL + GL Overlap", weekName: "Wk 4 — ESL Live + GL Master", dayLabel: "ESL 5-DAY DATA", badge: "Data", badgeClass: "badge-blue", cardClass: "card-left blue", deliverable: "ESL 5-day data pull · Save rate verdict · Content adjust", sub: "If save rate < 3%, shift content strategy toward ESL.", nn: ARC1_NN, dropLabel: "Days to GL", dropDate: "2026-05-23" },
  "2026-05-15": { arc: "1", phase: "ESL + GL Overlap", weekName: "Wk 4 — ESL Live + GL Master", dayLabel: "ESL COMPLIANCE", badge: "Compliance", badgeClass: "badge-purple", cardClass: "card-left purple", deliverable: "ESL registrations: ASCAP, MLC, Songtrust, Musixmatch, SoundExchange", sub: "Thursday compliance block. Pull ISRC from Amuse first.", nn: ARC1_NN, dropLabel: "Days to GL", dropDate: "2026-05-23" },

  // ═══ GL CAMPAIGN (May 16 – Jun 5) ═══
  "2026-05-16": { arc: "1", phase: "GL Campaign — Pre-Release", weekName: "Wk 5 — GL Pre-Save", dayLabel: "UPLOAD GL TO AMUSE", badge: "Upload", badgeClass: "badge-green", cardClass: "card-left green", deliverable: "Upload Green Light to Amuse · Set release May 23", sub: "7 days ingestion. GL content prep begins.", warning: { type: "important", icon: "📋", text: "<strong>Single #2 upload.</strong> Screenshot ISRC page. Save for EP waterfall." }, nn: ARC1_NN, dropLabel: "Days to GL", dropDate: "2026-05-23" },
  "2026-05-17": { arc: "1", phase: "GL Campaign — Pre-Release", weekName: "Wk 5 — GL Pre-Save", dayLabel: "GL CONTENT PREP", badge: "Content", badgeClass: "badge-gold", cardClass: "card-left", deliverable: "Write GL captions · Schedule pre-save push", sub: "Every post ends: Green Light — May 23", nn: ARC1_NN, dropLabel: "Days to GL", dropDate: "2026-05-23" },
  "2026-05-18": { arc: "1", phase: "GL Campaign — Pre-Release", weekName: "Wk 5 — GL Pre-Save", dayLabel: "SUNDAY + DATA", badge: "Sunday", badgeClass: "badge-purple", cardClass: "card-left purple", deliverable: "Grief journal · ESL week 2 data · GL pre-save push", sub: "Sunday data pull + grief journal.", nn: FLATLINE_NN, dropLabel: "Days to GL", dropDate: "2026-05-23" },
  "2026-05-19": { arc: "1", phase: "GL Campaign — Pre-Release", weekName: "Wk 5 — GL Pre-Save", dayLabel: "GL EDITORIAL PITCH", badge: "Pitch", badgeClass: "badge-blue", cardClass: "card-left blue", deliverable: "Spotify for Artists: GL editorial pitch · GL teaser post", sub: "Pitch 4 days before release.", nn: ARC1_NN, dropLabel: "Days to GL", dropDate: "2026-05-23" },
  "2026-05-20": { arc: "1", phase: "GL Campaign — Pre-Release", weekName: "Wk 5 — GL Pre-Save", dayLabel: "GL CONTENT PUSH", badge: "Content", badgeClass: "badge-gold", cardClass: "card-left", deliverable: "GL world-building post · Cinematic visual", sub: "3 days to GL drop.", nn: ARC1_NN, dropLabel: "Days to GL", dropDate: "2026-05-23" },
  "2026-05-21": { arc: "1", phase: "GL Campaign — Pre-Release", weekName: "Wk 5 — GL Pre-Save", dayLabel: "GL CONTENT + DM PREP", badge: "Content", badgeClass: "badge-gold", cardClass: "card-left", deliverable: "Talk to 'Em: story behind GL · DM list refresh", sub: "Update DM list with ESL responders. Add new targets.", nn: ARC1_NN, dropLabel: "Days to GL", dropDate: "2026-05-23" },
  "2026-05-22": { arc: "1", phase: "GL Campaign — Pre-Release", weekName: "Wk 5 — GL Pre-Save", dayLabel: "EVE OF GL", badge: "Eve", badgeClass: "badge-orange", cardClass: "card-left orange", deliverable: "Final GL pre-save push · DM blitz list finalized · Ads staged", sub: "Tomorrow Single #2 drops. Release Radar trigger #2.", nn: ARC1_NN, dropLabel: "GL tomorrow", dropDate: "2026-05-23" },
  "2026-05-23": { arc: "1", phase: "GL Release Day", weekName: "Wk 5 — GL Drops", dayLabel: "GREEN LIGHT DROPS", badge: "Release", badgeClass: "badge-red", cardClass: "card-left red", deliverable: "GL live everywhere · Release post · DM Blitz Round 2", sub: "Build DM list from ESL responders. 50 DMs.", warning: { type: "important", icon: "🎉", text: "<strong>Single #2 is live.</strong> Release Radar trigger #2. Two singles in the wild. Momentum is compounding." }, nn: ["DoorDash AM block", "50 DMs (prioritize ESL responders)", "Do NOT check stats after 8 PM"], dropLabel: "Days to SF", dropDate: "2026-06-06" },
  "2026-05-24": { arc: "1", phase: "GL Campaign — Post-Release", weekName: "Wk 6 — GL Live + SF Master", dayLabel: "GL DAY 2", badge: "Momentum", badgeClass: "badge-red", cardClass: "card-left red", deliverable: "GL post-release content · Respond to DM engagement", sub: "Saturday. Let it breathe.", nn: FLATLINE_NN, dropLabel: "Days to SF", dropDate: "2026-06-06" },
  "2026-05-25": { arc: "1", phase: "GL Campaign — Post-Release", weekName: "Wk 6 — GL Live + SF Master", dayLabel: "SUNDAY REVIEW", badge: "Sunday", badgeClass: "badge-purple", cardClass: "card-left purple", deliverable: "Grief journal · GL 48-hr data · ESL 2-week data", sub: "Both singles running. Compare save rates.", nn: FLATLINE_NN, dropLabel: "Days to SF", dropDate: "2026-06-06" },
  "2026-05-26": { arc: "2", phase: "GL + SF Overlap", weekName: "Wk 6 — GL Live + SF Master", dayLabel: "MASTER SWEET FRUSTRATION", badge: "Master", badgeClass: "badge-green", cardClass: "card-left green", deliverable: "Master Sweet Frustration · Illangelo chain · QC", sub: "GL is live. Now lock SF master for Jun 6 drop.", nn: ARC2_NN, dropLabel: "Days to SF", dropDate: "2026-06-06" },
  "2026-05-27": { arc: "2", phase: "GL + SF Overlap", weekName: "Wk 6 — GL Live + SF Master", dayLabel: "SF STEMS + ARTWORK", badge: "Export", badgeClass: "badge-green", cardClass: "card-left green", deliverable: "Export SF stems · Begin SF cover art", sub: "All deliverables for Amuse upload.", nn: ARC2_NN, dropLabel: "Days to SF", dropDate: "2026-06-06" },
  "2026-05-28": { arc: "2", phase: "GL + SF Overlap", weekName: "Wk 6 — GL Live + SF Master", dayLabel: "GL 5-DAY DATA + SYNC", badge: "Data", badgeClass: "badge-blue", cardClass: "card-left blue", deliverable: "GL 5-day data · Begin sync pitching with ESL + GL", sub: "Two singles = enough catalog for initial sync outreach.", nn: ARC2_NN, dropLabel: "Days to SF", dropDate: "2026-06-06" },
  "2026-05-29": { arc: "2", phase: "GL + SF Overlap", weekName: "Wk 6 — GL Live + SF Master", dayLabel: "GL COMPLIANCE", badge: "Compliance", badgeClass: "badge-purple", cardClass: "card-left purple", deliverable: "GL registrations: ASCAP, MLC, Songtrust, Musixmatch, SoundExchange", sub: "Thursday compliance block.", nn: ARC2_NN, dropLabel: "Days to SF", dropDate: "2026-06-06" },

  // ═══ SF CAMPAIGN (May 30 – Jun 19) ═══
  "2026-05-30": { arc: "2", phase: "SF Campaign — Pre-Release", weekName: "Wk 7 — SF Pre-Save", dayLabel: "UPLOAD SF TO AMUSE", badge: "Upload", badgeClass: "badge-green", cardClass: "card-left green", deliverable: "Upload Sweet Frustration to Amuse · Set release Jun 6", sub: "Single #3 upload. Screenshot ISRC.", warning: { type: "important", icon: "📋", text: "<strong>Single #3 upload.</strong> Screenshot ISRC page. 3 of 4 waterfall ISRCs now secured." }, nn: ARC2_NN, dropLabel: "Days to SF", dropDate: "2026-06-06" },
  "2026-05-31": { arc: "2", phase: "SF Campaign — Pre-Release", weekName: "Wk 7 — SF Pre-Save", dayLabel: "SF CONTENT + DISCOVERY CHECK", badge: "Content", badgeClass: "badge-gold", cardClass: "card-left", deliverable: "SF captions · Check Discovery Mode eligibility for ESL", sub: "ESL 30-day mark approaching. If save rate > 3% and ML > 25K, opt in.", warning: { type: "important", icon: "⚠️", text: "<strong>ESL Discovery Mode window.</strong> Must opt in before Jun 8 (12AM UTC) for July 1 activation. Check eligibility." }, nn: ARC2_NN, dropLabel: "Days to SF", dropDate: "2026-06-06" },
  "2026-06-01": { arc: "2", phase: "SF Campaign — Pre-Release", weekName: "Wk 7 — SF Pre-Save", dayLabel: "SUNDAY + TRIPLE DATA", badge: "Sunday", badgeClass: "badge-purple", cardClass: "card-left purple", deliverable: "Grief journal · ESL month data · GL 9-day data · SF pre-save push", sub: "Three tracks in various campaign stages. Pull all numbers.", nn: FLATLINE_NN, dropLabel: "Days to SF", dropDate: "2026-06-06" },
  "2026-06-02": { arc: "2", phase: "SF Campaign — Pre-Release", weekName: "Wk 7 — SF Pre-Save", dayLabel: "SF EDITORIAL PITCH", badge: "Pitch", badgeClass: "badge-blue", cardClass: "card-left blue", deliverable: "Spotify for Artists: SF editorial pitch · SF teaser post", sub: "Pitch 4 days before release.", nn: ARC2_NN, dropLabel: "Days to SF", dropDate: "2026-06-06" },
  "2026-06-03": { arc: "2", phase: "SF Campaign — Pre-Release", weekName: "Wk 7 — SF Pre-Save", dayLabel: "SF CONTENT PUSH", badge: "Content", badgeClass: "badge-gold", cardClass: "card-left", deliverable: "SF world-building + cinematic visual", sub: "KAYTRANADA lane — lean into the groove.", nn: ARC2_NN, dropLabel: "Days to SF", dropDate: "2026-06-06" },
  "2026-06-04": { arc: "2", phase: "SF Campaign — Pre-Release", weekName: "Wk 7 — SF Pre-Save", dayLabel: "SF CONTENT + DM PREP", badge: "Content", badgeClass: "badge-gold", cardClass: "card-left", deliverable: "Talk to 'Em: story behind SF · DM list refresh", sub: "Update DM list. ESL + GL responders are warm leads now.", nn: ARC2_NN, dropLabel: "Days to SF", dropDate: "2026-06-06" },
  "2026-06-05": { arc: "2", phase: "SF Campaign — Pre-Release", weekName: "Wk 7 — SF Pre-Save", dayLabel: "EVE OF SF", badge: "Eve", badgeClass: "badge-orange", cardClass: "card-left orange", deliverable: "Final SF pre-save push · DM blitz list finalized · Ads staged", sub: "Tomorrow Single #3 drops. Release Radar trigger #3.", nn: ARC2_NN, dropLabel: "SF tomorrow", dropDate: "2026-06-06" },
  "2026-06-06": { arc: "2", phase: "SF Release Day", weekName: "Wk 7 — SF Drops", dayLabel: "SWEET FRUSTRATION DROPS", badge: "Release", badgeClass: "badge-red", cardClass: "card-left red", deliverable: "SF live everywhere · Release post · DM Blitz Round 3", sub: "Three singles in the wild. Momentum is real.", warning: { type: "important", icon: "🎉", text: "<strong>Single #3 is live.</strong> Release Radar trigger #3. Three of four waterfall positions locked." }, nn: ["DoorDash AM block", "50 DMs (ESL + GL responders = warm list)", "Do NOT check stats after 8 PM"], dropLabel: "Days to EP", dropDate: "2026-06-20" },
  "2026-06-07": { arc: "2", phase: "SF Campaign — Post-Release", weekName: "Wk 8 — SF Live + EP Prep", dayLabel: "SF DAY 2", badge: "Momentum", badgeClass: "badge-red", cardClass: "card-left red", deliverable: "SF post-release content", sub: "Saturday. Let it breathe.", nn: FLATLINE_NN, dropLabel: "Days to EP", dropDate: "2026-06-20" },
  "2026-06-08": { arc: "2", phase: "SF Campaign — Post-Release", weekName: "Wk 8 — SF Live + EP Prep", dayLabel: "SUNDAY + FULL CATALOG DATA", badge: "Sunday", badgeClass: "badge-purple", cardClass: "card-left purple", deliverable: "Grief journal · All 3 singles data pull · Discovery Mode opt-in deadline check", sub: "ESL Discovery Mode: LAST DAY to opt in before 12AM UTC for July 1 activation.", warning: { type: "important", icon: "⚠️", text: "<strong>DISCOVERY MODE DEADLINE for ESL.</strong> If monthly listeners > 25K and save rate > 3%, opt in TODAY before midnight UTC." }, nn: FLATLINE_NN, dropLabel: "Days to EP", dropDate: "2026-06-20" },
  "2026-06-09": { arc: "2", phase: "EP Prep", weekName: "Wk 8 — SF Live + EP Prep", dayLabel: "MASTER WU2", badge: "Master", badgeClass: "badge-green", cardClass: "card-left green", deliverable: "Master Want U 2 · Illangelo chain · QC", sub: "Last track to master. EP-exclusive — make it count.", nn: ARC2_NN, dropLabel: "Days to EP", dropDate: "2026-06-20" },
  "2026-06-10": { arc: "2", phase: "EP Prep", weekName: "Wk 8 — SF Live + EP Prep", dayLabel: "WU2 STEMS + EP ARTWORK", badge: "Export", badgeClass: "badge-green", cardClass: "card-left green", deliverable: "Export WU2 stems · Finalize EP cover art", sub: "EP artwork: 3000x3000, no logos. Evolution of single covers — same universe.", nn: ARC2_NN, dropLabel: "Days to EP", dropDate: "2026-06-20" },
  "2026-06-11": { arc: "2", phase: "EP Prep", weekName: "Wk 8 — SF Live + EP Prep", dayLabel: "SF 5-DAY DATA + EP METADATA", badge: "Data", badgeClass: "badge-blue", cardClass: "card-left blue", deliverable: "SF 5-day data · Finalize EP metadata + track sequence", sub: "Sequence: SEE ME → ESL → GL → SF → WU2. Verify all ISRCs from singles.", nn: ARC2_NN, dropLabel: "Days to EP", dropDate: "2026-06-20" },
  "2026-06-12": { arc: "2", phase: "EP Prep", weekName: "Wk 8 — SF Live + EP Prep", dayLabel: "SF COMPLIANCE", badge: "Compliance", badgeClass: "badge-purple", cardClass: "card-left purple", deliverable: "SF registrations: ASCAP, MLC, Songtrust, Musixmatch, SoundExchange", sub: "Thursday compliance block.", nn: ARC2_NN, dropLabel: "Days to EP", dropDate: "2026-06-20" },

  // ═══ EP CAMPAIGN (Jun 13 – Jun 27) ═══
  "2026-06-13": { arc: "2", phase: "EP Campaign — Upload", weekName: "Wk 9 — EP Upload", dayLabel: "EP AMUSE UPLOAD", badge: "Upload", badgeClass: "badge-green", cardClass: "card-left green", deliverable: "Upload 5-track ALL LOVE EP to Amuse · Set release Jun 20", sub: "ISRC WATERFALL: Enter SEE ME, ESL, GL, SF ISRCs from their single uploads onto corresponding EP tracks. WU2 gets new ISRC.", warning: { type: "important", icon: "📋", text: "<strong>ISRC WATERFALL.</strong> Enter all 4 existing ISRCs (SEE ME + 3 singles) on the EP tracks. WU2 is new. This preserves ALL stream counts." }, nn: ARC2_NN, dropLabel: "Days to EP", dropDate: "2026-06-20" },
  "2026-06-14": { arc: "2", phase: "EP Campaign — Pre-Release", weekName: "Wk 9 — EP Upload", dayLabel: "EP EDITORIAL PITCH", badge: "Pitch", badgeClass: "badge-blue", cardClass: "card-left blue", deliverable: "Spotify for Artists: EP editorial pitch · WU2 as featured track", sub: "Pitch the EP entity. Highlight WU2 as the exclusive new track.", nn: ARC2_NN, dropLabel: "Days to EP", dropDate: "2026-06-20" },
  "2026-06-15": { arc: "2", phase: "EP Campaign — Pre-Release", weekName: "Wk 9 — EP Upload", dayLabel: "SUNDAY + EP CONTENT PREP", badge: "Sunday", badgeClass: "badge-purple", cardClass: "card-left purple", deliverable: "Grief journal · EP captions · Tracklist reveal strategy", sub: "Sunday. 5 days to EP. Tease WU2 as the never-before-heard track.", nn: FLATLINE_NN, dropLabel: "Days to EP", dropDate: "2026-06-20" },
  "2026-06-16": { arc: "2", phase: "EP Campaign — Pre-Release", weekName: "Wk 9 — EP Pre-Save", dayLabel: "EP TEASER: TRACKLIST", badge: "Content", badgeClass: "badge-gold", cardClass: "card-left", deliverable: "Tracklist reveal post · '5 tracks. June 20. ALL LOVE.'", sub: "The hype pivot. 3 tracks they know, 1 they've been waiting for, 1 surprise.", nn: ARC2_NN, dropLabel: "Days to EP", dropDate: "2026-06-20" },
  "2026-06-17": { arc: "2", phase: "EP Campaign — Pre-Release", weekName: "Wk 9 — EP Pre-Save", dayLabel: "EP CONTENT PUSH", badge: "Content", badgeClass: "badge-gold", cardClass: "card-left", deliverable: "World-building: 'The world of ALL LOVE' · Cinematic visual", sub: "The EP as a body of work, not just a playlist.", nn: ARC2_NN, dropLabel: "Days to EP", dropDate: "2026-06-20" },
  "2026-06-18": { arc: "2", phase: "EP Campaign — Pre-Release", weekName: "Wk 9 — EP Pre-Save", dayLabel: "WU2 SNIPPET", badge: "Teaser", badgeClass: "badge-red", cardClass: "card-left red", deliverable: "WU2 snippet/teaser · 'Only on the EP'", sub: "Hook for EP-exclusive content. Make them need to hear the full thing.", nn: ARC2_NN, dropLabel: "Days to EP", dropDate: "2026-06-20" },
  "2026-06-19": { arc: "2", phase: "EP Campaign — Pre-Release", weekName: "Wk 9 — EP Pre-Save", dayLabel: "EVE OF EP", badge: "Eve", badgeClass: "badge-orange", cardClass: "card-left orange", deliverable: "Talk to 'Em: What ALL LOVE means · Final DM blitz list · Ads staged", sub: "Tomorrow the full project drops. Every single + WU2 = complete.", nn: ARC2_NN, dropLabel: "EP tomorrow", dropDate: "2026-06-20" },
  "2026-06-20": { arc: "2", phase: "EP Release Day", weekName: "Wk 10 — ALL LOVE EP", dayLabel: "ALL LOVE EP DROPS", badge: "Release", badgeClass: "badge-red", cardClass: "card-left red", deliverable: "ALL LOVE EP live · Release post · DM Blitz Round 4 · Spotify Ads", sub: "Release Radar trigger #4. Full project in the world.", warning: { type: "important", icon: "🎉", text: "<strong>ALL LOVE EP is live.</strong> 4 Release Radar triggers across 6 weeks. Check if streams from singles carried over via ISRC waterfall." }, nn: ["DoorDash AM block", "50 DMs — full warm list from 3 prior blitzes", "Spotify Ads live", "Do NOT check stats after 8 PM"], dropLabel: "Days to CREAM", dropDate: "2026-07-10" },
  "2026-06-21": { arc: "3", phase: "EP Campaign — Post-Release", weekName: "Wk 10 — EP Live", dayLabel: "EP DAY 2", badge: "Momentum", badgeClass: "badge-red", cardClass: "card-left red", deliverable: "EP post-release content · Respond to DM engagement", sub: "Saturday. Let it breathe.", nn: FLATLINE_NN, dropLabel: "Days to CREAM", dropDate: "2026-07-10" },
  "2026-06-22": { arc: "3", phase: "EP Campaign — Post-Release", weekName: "Wk 10 — EP Live", dayLabel: "SUNDAY + FULL CATALOG DATA", badge: "Sunday", badgeClass: "badge-purple", cardClass: "card-left purple", deliverable: "Grief journal · Full catalog data pull · EP 48-hr numbers", sub: "Every track's save rate, SPL, playlist adds.", nn: FLATLINE_NN, dropLabel: "Days to CREAM", dropDate: "2026-07-10" },
  "2026-06-23": { arc: "3", phase: "Compound", weekName: "Wk 10 — EP Live", dayLabel: "SYNC PITCHING — FULL CATALOG", badge: "Pitch", badgeClass: "badge-blue", cardClass: "card-left blue", deliverable: "Full 5-track EP + SEE ME to sync agencies", sub: "Clean rights · instrumentals · stems · pitch deck. 6 tracks total.", nn: ARC3_NN, dropLabel: "Days to CREAM", dropDate: "2026-07-10" },
  "2026-06-24": { arc: "3", phase: "Compound", weekName: "Wk 10 — EP Live", dayLabel: "WU2 + EP COMPLIANCE", badge: "Compliance", badgeClass: "badge-purple", cardClass: "card-left purple", deliverable: "WU2 registrations + EP-level registrations: ASCAP, MLC, Songtrust", sub: "All tracks now registered. Full catalog clean.", nn: ARC3_NN, dropLabel: "Days to CREAM", dropDate: "2026-07-10" },
  "2026-06-25": { arc: "3", phase: "Compound", weekName: "Wk 10 — EP Live", dayLabel: "EP 5-DAY DATA", badge: "Data", badgeClass: "badge-blue", cardClass: "card-left blue", deliverable: "EP 5-day data pull · WU2 save rate (new track signal) · Discovery Mode check", sub: "Compare WU2 (EP-exclusive) vs singles save rates — measures EP pull.", nn: ARC3_NN, dropLabel: "Days to CREAM", dropDate: "2026-07-10" },
  "2026-06-26": { arc: "3", phase: "Compound", weekName: "Wk 10 — EP Live", dayLabel: "LIVE BOOKING OUTREACH", badge: "Business", badgeClass: "badge-green", cardClass: "card-left green", deliverable: "Denver venue outreach · 3 venues minimum · Milwaukee venue check", sub: "Position around summer. Use EP + full catalog as leverage.", nn: ARC3_NN, dropLabel: "Days to CREAM", dropDate: "2026-07-10" },
  "2026-06-27": { arc: "3", phase: "Compound", weekName: "Wk 10 — EP Live", dayLabel: "WEEK 10 REVIEW", badge: "Review", badgeClass: "badge-gold", cardClass: "card-left", deliverable: "EP week 1 data · Pop score · Follower delta · Waterfall verification", sub: "Did all single streams carry over to EP? Check total stream counts.", nn: ARC3_NN, dropLabel: "Days to CREAM", dropDate: "2026-07-10" },

  // ═══ COMPOUND + CREAM DECISION (Jun 28 – Jul 17) ═══
  "2026-06-28": { arc: "3", phase: "Compound", weekName: "Wk 11 — Summer", dayLabel: "SUMMER ARC BEGINS", badge: "Summer", badgeClass: "badge-purple", cardClass: "card-left purple", deliverable: "Summer content arc · travel · sessions · visuals", sub: "Behind-the-scenes becomes a pillar. EP is compounding.", nn: ARC3_NN, dropLabel: "Days to CREAM", dropDate: "2026-07-10" },
  "2026-06-29": { arc: "3", phase: "Compound", weekName: "Wk 11 — Summer", dayLabel: "SUNDAY REVIEW", badge: "Sunday", badgeClass: "badge-purple", cardClass: "card-left purple", deliverable: "Grief journal · Week 11 protocol check", sub: "GL + SF Discovery Mode check — opt in if eligible.", nn: FLATLINE_NN, dropLabel: "Days to CREAM", dropDate: "2026-07-10" },
  "2026-06-30": { arc: "3", phase: "Compound", weekName: "Wk 11 — Summer", dayLabel: "MONTH END REVIEW", badge: "Review", badgeClass: "badge-gold", cardClass: "card-left", deliverable: "June numbers · Revenue (DoorDash + streaming) · Follower growth", sub: "Full June audit. 4 releases this month.", nn: ARC3_NN, dropLabel: "Days to CREAM", dropDate: "2026-07-10" },
  "2026-07-01": { arc: "3", phase: "Compound", weekName: "Wk 11 — Summer", dayLabel: "JULY BEGINS", badge: "Month", badgeClass: "badge-gold", cardClass: "card-left", deliverable: "Q3 strategy · CREAM pre-production decision ramp", sub: "Discovery Mode for ESL should activate today if opted in Jun 8.", nn: ARC3_NN, dropLabel: "Days to CREAM", dropDate: "2026-07-10" },
  "2026-07-02": { arc: "3", phase: "Compound", weekName: "Wk 11 — Summer", dayLabel: "CONTENT SURGE", badge: "Sustain", badgeClass: "badge-gold", cardClass: "card-left", deliverable: "Summer visual content · travel photography", sub: "New visual language for Q3.", nn: ARC3_NN, dropLabel: "Days to CREAM", dropDate: "2026-07-10" },
  "2026-07-03": { arc: "3", phase: "Compound", weekName: "Wk 11 — Summer", dayLabel: "LIVE REHEARSAL", badge: "Business", badgeClass: "badge-green", cardClass: "card-left green", deliverable: "First full setlist rehearsal · arrangement for live", sub: "Adapt production for stage.", nn: ARC3_NN, dropLabel: "Days to CREAM", dropDate: "2026-07-10" },
  "2026-07-04": { arc: "3", phase: "Compound", weekName: "Wk 12 — Summer", dayLabel: "INDEPENDENCE DAY", badge: "Rest", badgeClass: "badge-gold", cardClass: "card-left", deliverable: "Rest + family · one post only · partner time", sub: "Recovery is production.", nn: ["Rest", "Partner time", "No scroll"], dropLabel: "Days to CREAM", dropDate: "2026-07-10" },
  "2026-07-05": { arc: "3", phase: "Compound", weekName: "Wk 12 — Summer", dayLabel: "SUNDAY REVIEW", badge: "Sunday", badgeClass: "badge-purple", cardClass: "card-left purple", deliverable: "Grief journal · Week 12 check", sub: "2 weeks to 90-day review. CREAM inputs aggregating.", nn: FLATLINE_NN, dropLabel: "Days to CREAM", dropDate: "2026-07-10" },
  "2026-07-06": { arc: "3", phase: "Compound", weekName: "Wk 12 — Summer", dayLabel: "CREAM DATA PULL", badge: "Data", badgeClass: "badge-blue", cardClass: "card-left blue", deliverable: "Full catalog data · EP 2-week numbers · Save rates across all 5 tracks", sub: "Inputs for CREAM decision.", nn: ARC3_NN, dropLabel: "Days to CREAM", dropDate: "2026-07-10" },
  "2026-07-07": { arc: "3", phase: "Compound", weekName: "Wk 12 — Summer", dayLabel: "LIVE BOOKING CONFIRMED", badge: "Business", badgeClass: "badge-green", cardClass: "card-left green", deliverable: "First summer live date confirmed · promo in motion", sub: "Announce within 24 hrs of venue confirmation.", nn: ARC3_NN, dropLabel: "Days to CREAM", dropDate: "2026-07-10" },
  "2026-07-08": { arc: "3", phase: "Compound", weekName: "Wk 12 — Summer", dayLabel: "CONTENT SUSTAIN", badge: "Sustain", badgeClass: "badge-gold", cardClass: "card-left", deliverable: "Daily content · summer visual arc", sub: "EP still compounding.", nn: ARC3_NN, dropLabel: "Days to CREAM", dropDate: "2026-07-10" },
  "2026-07-09": { arc: "3", phase: "Compound", weekName: "Wk 12 — Summer", dayLabel: "CREAM EVE", badge: "Decision", badgeClass: "badge-orange", cardClass: "card-left orange", deliverable: "All CREAM inputs aggregated · go/no-go framework ready", sub: "Tomorrow is the call.", nn: ARC3_NN, dropLabel: "CREAM call tomorrow", dropDate: "2026-07-10" },
  "2026-07-10": { arc: "3", phase: "Compound", weekName: "Wk 12 — Summer", dayLabel: "CREAM DECISION", badge: "Decision", badgeClass: "badge-red", cardClass: "card-left red", deliverable: "Ship CREAM Q3 or push to Q4? · Data-driven call", sub: "Waterfall data + save rates + live traction + bandwidth = signal.", warning: { type: "important", icon: "⚡", text: "<strong>No vibes on this one.</strong> Use the numbers. EP pop delta + save rate + live traction = signal." }, nn: ["Data pulled", "Decision documented", "Decision shared with partner"], dropLabel: "Days to 90-day review", dropDate: "2026-07-17" },

  // ═══ WEEK 13: IDENTITY LOCK-IN ═══
  "2026-07-11": { arc: "3", phase: "Compound", weekName: "Wk 13 — Identity Lock", dayLabel: "POST-CREAM PIVOT", badge: "Execute", badgeClass: "badge-gold", cardClass: "card-left", deliverable: "Execute whichever CREAM call was made yesterday", sub: "Q3 plan solidifies.", nn: ARC3_NN, dropLabel: "Days to 90-day review", dropDate: "2026-07-17" },
  "2026-07-12": { arc: "3", phase: "Compound", weekName: "Wk 13 — Identity Lock", dayLabel: "SUNDAY + REVIEW PREP", badge: "Sunday", badgeClass: "badge-purple", cardClass: "card-left purple", deliverable: "Grief journal · Begin 90-day review data aggregation", sub: "Followers · monthly · pop · revenue · email · merch.", nn: FLATLINE_NN, dropLabel: "Days to 90-day review", dropDate: "2026-07-17" },
  "2026-07-13": { arc: "3", phase: "Compound", weekName: "Wk 13 — Identity Lock", dayLabel: "NORTH STAR CHECK", badge: "Check", badgeClass: "badge-gold", cardClass: "card-left", deliverable: "Compare 90-day numbers vs. SOVEREIGN_ACTION_PLAN targets", sub: "Hit · miss · surprise.", nn: ARC3_NN, dropLabel: "Days to 90-day review", dropDate: "2026-07-17" },
  "2026-07-14": { arc: "3", phase: "Compound", weekName: "Wk 13 — Identity Lock", dayLabel: "SYNC / LIVE / MERCH REVIEW", badge: "Review", badgeClass: "badge-gold", cardClass: "card-left", deliverable: "Three infra tracks audited · What's real? What stalled?", sub: "Decide Q3 priorities from the honest state.", nn: ARC3_NN, dropLabel: "Days to 90-day review", dropDate: "2026-07-17" },
  "2026-07-15": { arc: "3", phase: "Compound", weekName: "Wk 13 — Identity Lock", dayLabel: "SOVEREIGNTY PROTOCOL AUDIT", badge: "Audit", badgeClass: "badge-purple", cardClass: "card-left purple", deliverable: "90-day protocol audit: sobriety, release cadence, sleep, food", sub: "Honest · structural.", nn: ARC3_NN, dropLabel: "Days to 90-day review", dropDate: "2026-07-17" },
  "2026-07-16": { arc: "3", phase: "Compound", weekName: "Wk 13 — Identity Lock", dayLabel: "REVIEW DOC DRAFT", badge: "Draft", badgeClass: "badge-gold", cardClass: "card-left", deliverable: "Draft 90-day review doc · all data + all protocol in one place", sub: "Foundation for next 90 days.", nn: ARC3_NN, dropLabel: "Days to 90-day review", dropDate: "2026-07-17" },
  "2026-07-17": { arc: "3", phase: "Identity Locked", weekName: "Wk 13 — 90-Day Review", dayLabel: "90-DAY REVIEW", badge: "Review", badgeClass: "badge-gold", cardClass: "card-left", deliverable: "Full review · 4 Release Radar cycles documented · next 90 planned", sub: "The waterfall held · the engine is real · the system is yours.", warning: { type: "tip", icon: "🏁", text: "<strong>Arc complete.</strong> 4 singles + EP across 6 weeks. If the protocol held, the compounding is real. Document it." }, nn: ["Review doc complete", "Next 90 sketched", "Celebration — dinner with partner"], dropLabel: "90-day review", dropDate: "2026-07-17" },

  // ═══ ARC 3 — VAULT PRODUCTION BATCH (Jul 18-24) ═══
  "2026-07-18": {arc:"3",phase:"Vault Production Batch",weekName:"Wk 14 — Batch Recording",dayLabel:"TOPLINE DAY 1",badge:"Record",badgeClass:"badge-blue",cardClass:"card-left blue",deliverable:"Toplines — Like I Did + I Like Girls",sub:"Performer mode. Capture raw.",nn:["DoorDash + calisthenics", "One creative + one business deliverable", "2hr focus / 20min walk rhythm"],dropLabel:"Days to LID",dropDate:"2026-07-25"},
  "2026-07-19": {arc:"3",phase:"Vault Production Batch",weekName:"Wk 14 — Batch Recording",dayLabel:"TOPLINE DAY 2",badge:"Record",badgeClass:"badge-blue",cardClass:"card-left blue",deliverable:"Toplines — Worth It + Just Say So",sub:"Keep flowing.",nn:["DoorDash + calisthenics", "One creative + one business deliverable", "2hr focus / 20min walk rhythm"],dropLabel:"Days to LID",dropDate:"2026-07-25"},
  "2026-07-20": {arc:"3",phase:"Vault Production Batch",weekName:"Wk 14 — Batch Recording",dayLabel:"TOPLINE DAY 3",badge:"Record",badgeClass:"badge-blue",cardClass:"card-left blue",deliverable:"Toplines — Reconnect + overflow",sub:"Review all toplines end of day.",nn:["DoorDash + calisthenics", "One creative + one business deliverable", "2hr focus / 20min walk rhythm"],dropLabel:"Days to LID",dropDate:"2026-07-25"},
  "2026-07-21": {arc:"3",phase:"Vault Production Batch",weekName:"Wk 14 — Batch Recording",dayLabel:"RECORDING DAY 1",badge:"Record",badgeClass:"badge-blue",cardClass:"card-left blue",deliverable:"Full vocals — Like I Did + I Like Girls",sub:"Comp→de-breath→comp2. Batch mode.",nn:["DoorDash + calisthenics", "One creative + one business deliverable", "2hr focus / 20min walk rhythm"],dropLabel:"Days to LID",dropDate:"2026-07-25"},
  "2026-07-22": {arc:"3",phase:"Vault Production Batch",weekName:"Wk 14 — Batch Recording",dayLabel:"RECORDING DAY 2",badge:"Record",badgeClass:"badge-blue",cardClass:"card-left blue",deliverable:"Full vocals — Worth It + Just Say So",sub:"Same batch workflow.",nn:["DoorDash + calisthenics", "One creative + one business deliverable", "2hr focus / 20min walk rhythm"],dropLabel:"Days to LID",dropDate:"2026-07-25"},
  "2026-07-23": {arc:"3",phase:"Vault Production Batch",weekName:"Wk 14 — Batch Recording",dayLabel:"RECORDING DAY 3",badge:"Record",badgeClass:"badge-blue",cardClass:"card-left blue",deliverable:"Full vocals — Reconnect + finishing takes",sub:"All 5 tracks recorded today.",nn:["DoorDash + calisthenics", "One creative + one business deliverable", "2hr focus / 20min walk rhythm"],dropLabel:"Days to LID",dropDate:"2026-07-25"},
  "2026-07-24": {arc:"3",phase:"Vault Production Batch",weekName:"Wk 14 — Batch Recording",dayLabel:"RECORDING OVERFLOW + ROUGH MIX",badge:"Mix",badgeClass:"badge-blue",cardClass:"card-left blue",deliverable:"Overflow takes + start rough mix on Like I Did",sub:"Buffer day.",nn:["DoorDash + calisthenics", "One creative + one business deliverable", "2hr focus / 20min walk rhythm"],dropLabel:"Days to LID",dropDate:"2026-07-25"},
  // ═══ LIKE I DID LIFECYCLE ═══
  "2026-07-25": {arc:"3",phase:"Like I Did Release Day",weekName:"Wk 16 — Like I Did Drops",dayLabel:"LIKE I DID DROPS",badge:"Release",badgeClass:"badge-red",cardClass:"card-left red",deliverable:"Like I Did live · Meme account drops 3-5 LYRC edits · Surgical DMs",sub:"Vault single 1 of 5. Release Radar trigger.",warning:{type:"important",icon:"🎉",text:"<strong>Like I Did is live.</strong> Vault 1 of 5."},nn:["Surgical DMs only","Meme: 3-5 LYRC edits","No stats after 8 PM"],dropLabel:"Days to ILG",dropDate:"2026-08-08"},
  "2026-07-26": {arc:"3",phase:"Like I Did Post-Release",weekName:"Wk 16 — Like I Did Live",dayLabel:"SUNDAY REVIEW",badge:"Sunday",badgeClass:"badge-purple",cardClass:"card-left",deliverable:"Grief journal · Like I Did week-1 data · Rest",sub:"Day 8 of 14-day lifecycle.",nn:["Calisthenics — even if pointless", "Meditation / mudras — keep the slot", "One content piece max (ceiling, not floor)"],dropLabel:"Days to ILG",dropDate:"2026-08-08"},
  "2026-07-27": {arc:"3",phase:"Like I Did Post-Release",weekName:"Wk 16 — Like I Did Live",dayLabel:"DM FOLLOW-UP + DATA",badge:"Data",badgeClass:"badge-blue",cardClass:"card-left",deliverable:"Like I Did 48-hr data · DM follow-up",sub:"Day 9 of 14-day lifecycle.",nn:["DoorDash + calisthenics", "One creative + one business deliverable", "2hr focus / 20min walk rhythm"],dropLabel:"Days to ILG",dropDate:"2026-08-08"},
  "2026-07-28": {arc:"3",phase:"Like I Did Post-Release",weekName:"Wk 16 — Like I Did Live",dayLabel:"DATA PULL",badge:"Data",badgeClass:"badge-blue",cardClass:"card-left",deliverable:"Like I Did 3-day save rate check · Catalog note",sub:"Day 10 of 14-day lifecycle.",nn:["DoorDash + calisthenics", "One creative + one business deliverable", "2hr focus / 20min walk rhythm"],dropLabel:"Days to ILG",dropDate:"2026-08-08"},
  "2026-07-29": {arc:"3",phase:"Like I Did Post-Release",weekName:"Wk 16 — Like I Did Live",dayLabel:"COMPOUND + MEME",badge:"Sustain",badgeClass:"badge-gold",cardClass:"card-left",deliverable:"Meme account compound posts · Sync pitch outreach",sub:"Day 11 of 14-day lifecycle.",nn:["DoorDash + calisthenics", "One creative + one business deliverable", "2hr focus / 20min walk rhythm"],dropLabel:"Days to ILG",dropDate:"2026-08-08"},
  "2026-07-30": {arc:"3",phase:"Like I Did Post-Release",weekName:"Wk 16 — Like I Did Live",dayLabel:"COMPLIANCE",badge:"Compliance",badgeClass:"badge-purple",cardClass:"card-left",deliverable:"Like I Did compliance: ASCAP, MLC, Songtrust, Musixmatch",sub:"Day 12 of 14-day lifecycle.",nn:["DoorDash + calisthenics", "One creative + one business deliverable", "2hr focus / 20min walk rhythm"],dropLabel:"Days to ILG",dropDate:"2026-08-08"},
  "2026-07-31": {arc:"3",phase:"Like I Did Post-Release",weekName:"Wk 16 — Like I Did Live",dayLabel:"COMPOUND + CREAM PREP",badge:"Sustain",badgeClass:"badge-gold",cardClass:"card-left",deliverable:"Compound: playlist outreach · Sync pitching",sub:"Day 13 of 14-day lifecycle.",nn:["DoorDash + calisthenics", "One creative + one business deliverable", "2hr focus / 20min walk rhythm"],dropLabel:"Days to ILG",dropDate:"2026-08-08"},
  "2026-08-01": {arc:"3",phase:"Like I Did Post-Release",weekName:"Wk 16 — Like I Did Live",dayLabel:"COMPOUND + CREAM PREP",badge:"Sustain",badgeClass:"badge-gold",cardClass:"card-left",deliverable:"Compound: playlist outreach · Sync pitching",sub:"Day 14 of 14-day lifecycle.",nn:["DoorDash + calisthenics", "One creative + one business deliverable", "2hr focus / 20min walk rhythm"],dropLabel:"Days to ILG",dropDate:"2026-08-08"},
  // ═══ I LIKE GIRLS LIFECYCLE ═══
  "2026-08-02": {arc:"3",phase:"I Like Girls Campaign",weekName:"Wk 17 — I Like Girls Pre-Release",dayLabel:"SUNDAY — PRE-RELEASE REST",badge:"Sunday",badgeClass:"badge-purple",cardClass:"card-left",deliverable:"Grief journal · I Like Girls pre-release check · Rest",sub:"T-6 to release.",nn:["Calisthenics — even if pointless", "Meditation / mudras — keep the slot", "One content piece max (ceiling, not floor)"],dropLabel:"Days to WI",dropDate:"2026-08-22"},
  "2026-08-03": {arc:"3",phase:"I Like Girls Campaign",weekName:"Wk 17 — I Like Girls Pre-Release",dayLabel:"CONTENT SPRINT",badge:"Content",badgeClass:"badge-gold",cardClass:"card-left",deliverable:"World-building content · Meme posts",sub:"T-5 to release.",nn:["DoorDash + calisthenics", "One creative + one business deliverable", "2hr focus / 20min walk rhythm"],dropLabel:"Days to WI",dropDate:"2026-08-22"},
  "2026-08-04": {arc:"3",phase:"I Like Girls Campaign",weekName:"Wk 17 — I Like Girls Pre-Release",dayLabel:"CONTENT + DM PREP",badge:"Content",badgeClass:"badge-gold",cardClass:"card-left",deliverable:"Surgical DM prep (sync sups + curators only)",sub:"T-4 to release.",nn:["DoorDash + calisthenics", "One creative + one business deliverable", "2hr focus / 20min walk rhythm"],dropLabel:"Days to WI",dropDate:"2026-08-22"},
  "2026-08-05": {arc:"3",phase:"I Like Girls Campaign",weekName:"Wk 17 — I Like Girls Pre-Release",dayLabel:"EDITORIAL PITCH",badge:"Pitch",badgeClass:"badge-blue",cardClass:"card-left",deliverable:"Spotify editorial pitch · Teaser post",sub:"T-3 to release.",nn:["DoorDash + calisthenics", "One creative + one business deliverable", "2hr focus / 20min walk rhythm"],dropLabel:"Days to WI",dropDate:"2026-08-22"},
  "2026-08-06": {arc:"3",phase:"I Like Girls Campaign",weekName:"Wk 17 — I Like Girls Pre-Release",dayLabel:"EVE OF RELEASE",badge:"Eve",badgeClass:"badge-orange",cardClass:"card-left",deliverable:"Final pre-save push · Everything staged for tomorrow",sub:"T-2 to release.",nn:["DoorDash + calisthenics", "One creative + one business deliverable", "2hr focus / 20min walk rhythm"],dropLabel:"Days to WI",dropDate:"2026-08-22"},
  "2026-08-07": {arc:"3",phase:"I Like Girls Campaign",weekName:"Wk 17 — I Like Girls Pre-Release",dayLabel:"EVE OF I LIKE GIRLS",badge:"Eve",badgeClass:"badge-orange",cardClass:"card-left",deliverable:"Final pre-save push for I Like Girls · DM list finalized · Ads staged",sub:"T-1 to release. Tomorrow I Like Girls drops.",nn:["DoorDash + calisthenics", "One creative + one business deliverable", "2hr focus / 20min walk rhythm"],dropLabel:"Days to WI",dropDate:"2026-08-22"},
  "2026-08-08": {arc:"3",phase:"I Like Girls Release Day",weekName:"Wk 18 — I Like Girls Drops",dayLabel:"I LIKE GIRLS DROPS",badge:"Release",badgeClass:"badge-red",cardClass:"card-left red",deliverable:"I Like Girls live · Meme account drops 3-5 LYRC edits · Surgical DMs",sub:"Vault single 2 of 5. Release Radar trigger.",warning:{type:"important",icon:"🎉",text:"<strong>I Like Girls is live.</strong> Vault 2 of 5."},nn:["Surgical DMs only","Meme: 3-5 LYRC edits","No stats after 8 PM"],dropLabel:"Days to WI",dropDate:"2026-08-22"},
  "2026-08-09": {arc:"3",phase:"I Like Girls Post-Release",weekName:"Wk 18 — I Like Girls Live",dayLabel:"SUNDAY REVIEW",badge:"Sunday",badgeClass:"badge-purple",cardClass:"card-left",deliverable:"Grief journal · I Like Girls week-1 data · Rest",sub:"Day 8 of 14-day lifecycle.",nn:["Calisthenics — even if pointless", "Meditation / mudras — keep the slot", "One content piece max (ceiling, not floor)"],dropLabel:"Days to WI",dropDate:"2026-08-22"},
  "2026-08-10": {arc:"3",phase:"I Like Girls Post-Release",weekName:"Wk 18 — I Like Girls Live",dayLabel:"DM FOLLOW-UP + DATA",badge:"Data",badgeClass:"badge-blue",cardClass:"card-left",deliverable:"I Like Girls 48-hr data · DM follow-up",sub:"Day 9 of 14-day lifecycle.",nn:["DoorDash + calisthenics", "One creative + one business deliverable", "2hr focus / 20min walk rhythm"],dropLabel:"Days to WI",dropDate:"2026-08-22"},
  "2026-08-11": {arc:"3",phase:"I Like Girls Post-Release",weekName:"Wk 18 — I Like Girls Live",dayLabel:"DATA PULL",badge:"Data",badgeClass:"badge-blue",cardClass:"card-left",deliverable:"I Like Girls 3-day save rate check · Catalog note",sub:"Day 10 of 14-day lifecycle.",nn:["DoorDash + calisthenics", "One creative + one business deliverable", "2hr focus / 20min walk rhythm"],dropLabel:"Days to WI",dropDate:"2026-08-22"},
  "2026-08-12": {arc:"3",phase:"I Like Girls Post-Release",weekName:"Wk 18 — I Like Girls Live",dayLabel:"COMPOUND + MEME",badge:"Sustain",badgeClass:"badge-gold",cardClass:"card-left",deliverable:"Meme account compound posts · Sync pitch outreach",sub:"Day 11 of 14-day lifecycle.",nn:["DoorDash + calisthenics", "One creative + one business deliverable", "2hr focus / 20min walk rhythm"],dropLabel:"Days to WI",dropDate:"2026-08-22"},
  "2026-08-13": {arc:"3",phase:"I Like Girls Post-Release",weekName:"Wk 18 — I Like Girls Live",dayLabel:"COMPLIANCE",badge:"Compliance",badgeClass:"badge-purple",cardClass:"card-left",deliverable:"I Like Girls compliance: ASCAP, MLC, Songtrust, Musixmatch",sub:"Day 12 of 14-day lifecycle.",nn:["DoorDash + calisthenics", "One creative + one business deliverable", "2hr focus / 20min walk rhythm"],dropLabel:"Days to WI",dropDate:"2026-08-22"},
  "2026-08-14": {arc:"3",phase:"I Like Girls Post-Release",weekName:"Wk 18 — I Like Girls Live",dayLabel:"COMPOUND + CREAM PREP",badge:"Sustain",badgeClass:"badge-gold",cardClass:"card-left",deliverable:"Compound: playlist outreach · Sync pitching",sub:"Day 13 of 14-day lifecycle.",nn:["DoorDash + calisthenics", "One creative + one business deliverable", "2hr focus / 20min walk rhythm"],dropLabel:"Days to WI",dropDate:"2026-08-22"},
  "2026-08-15": {arc:"3",phase:"I Like Girls Post-Release",weekName:"Wk 18 — I Like Girls Live",dayLabel:"COMPOUND + CREAM PREP",badge:"Sustain",badgeClass:"badge-gold",cardClass:"card-left",deliverable:"Compound: playlist outreach · Sync pitching",sub:"Day 14 of 14-day lifecycle.",nn:["DoorDash + calisthenics", "One creative + one business deliverable", "2hr focus / 20min walk rhythm"],dropLabel:"Days to WI",dropDate:"2026-08-22"},
  // ═══ WORTH IT LIFECYCLE ═══
  "2026-08-16": {arc:"3",phase:"Worth It Campaign",weekName:"Wk 19 — Worth It Pre-Release",dayLabel:"SUNDAY — PRE-RELEASE REST",badge:"Sunday",badgeClass:"badge-purple",cardClass:"card-left",deliverable:"Grief journal · Worth It pre-release check · Rest",sub:"T-6 to release.",nn:["Calisthenics — even if pointless", "Meditation / mudras — keep the slot", "One content piece max (ceiling, not floor)"],dropLabel:"Days to JSS",dropDate:"2026-09-05"},
  "2026-08-17": {arc:"3",phase:"Worth It Campaign",weekName:"Wk 19 — Worth It Pre-Release",dayLabel:"CONTENT SPRINT",badge:"Content",badgeClass:"badge-gold",cardClass:"card-left",deliverable:"World-building content · Meme posts",sub:"T-5 to release.",nn:["DoorDash + calisthenics", "One creative + one business deliverable", "2hr focus / 20min walk rhythm"],dropLabel:"Days to JSS",dropDate:"2026-09-05"},
  "2026-08-18": {arc:"3",phase:"Worth It Campaign",weekName:"Wk 19 — Worth It Pre-Release",dayLabel:"CONTENT + DM PREP",badge:"Content",badgeClass:"badge-gold",cardClass:"card-left",deliverable:"Surgical DM prep (sync sups + curators only)",sub:"T-4 to release.",nn:["DoorDash + calisthenics", "One creative + one business deliverable", "2hr focus / 20min walk rhythm"],dropLabel:"Days to JSS",dropDate:"2026-09-05"},
  "2026-08-19": {arc:"3",phase:"Worth It Campaign",weekName:"Wk 19 — Worth It Pre-Release",dayLabel:"EDITORIAL PITCH",badge:"Pitch",badgeClass:"badge-blue",cardClass:"card-left",deliverable:"Spotify editorial pitch · Teaser post",sub:"T-3 to release.",nn:["DoorDash + calisthenics", "One creative + one business deliverable", "2hr focus / 20min walk rhythm"],dropLabel:"Days to JSS",dropDate:"2026-09-05"},
  "2026-08-20": {arc:"3",phase:"Worth It Campaign",weekName:"Wk 19 — Worth It Pre-Release",dayLabel:"EVE OF RELEASE",badge:"Eve",badgeClass:"badge-orange",cardClass:"card-left",deliverable:"Final pre-save push · Everything staged for tomorrow",sub:"T-2 to release.",nn:["DoorDash + calisthenics", "One creative + one business deliverable", "2hr focus / 20min walk rhythm"],dropLabel:"Days to JSS",dropDate:"2026-09-05"},
  "2026-08-21": {arc:"3",phase:"Worth It Campaign",weekName:"Wk 19 — Worth It Pre-Release",dayLabel:"EVE OF WORTH IT",badge:"Eve",badgeClass:"badge-orange",cardClass:"card-left",deliverable:"Final pre-save push for Worth It · DM list finalized · Ads staged",sub:"T-1 to release. Tomorrow Worth It drops.",nn:["DoorDash + calisthenics", "One creative + one business deliverable", "2hr focus / 20min walk rhythm"],dropLabel:"Days to JSS",dropDate:"2026-09-05"},
  "2026-08-22": {arc:"3",phase:"Worth It Release Day",weekName:"Wk 20 — Worth It Drops",dayLabel:"WORTH IT DROPS",badge:"Release",badgeClass:"badge-red",cardClass:"card-left red",deliverable:"Worth It live · Meme account drops 3-5 LYRC edits · Surgical DMs",sub:"Vault single 3 of 5. Release Radar trigger.",warning:{type:"important",icon:"🎉",text:"<strong>Worth It is live.</strong> Vault 3 of 5."},nn:["Surgical DMs only","Meme: 3-5 LYRC edits","No stats after 8 PM"],dropLabel:"Days to JSS",dropDate:"2026-09-05"},
  "2026-08-23": {arc:"3",phase:"Worth It Post-Release",weekName:"Wk 20 — Worth It Live",dayLabel:"SUNDAY REVIEW",badge:"Sunday",badgeClass:"badge-purple",cardClass:"card-left",deliverable:"Grief journal · Worth It week-1 data · Rest",sub:"Day 8 of 14-day lifecycle.",nn:["Calisthenics — even if pointless", "Meditation / mudras — keep the slot", "One content piece max (ceiling, not floor)"],dropLabel:"Days to JSS",dropDate:"2026-09-05"},
  "2026-08-24": {arc:"3",phase:"Worth It Post-Release",weekName:"Wk 20 — Worth It Live",dayLabel:"DM FOLLOW-UP + DATA",badge:"Data",badgeClass:"badge-blue",cardClass:"card-left",deliverable:"Worth It 48-hr data · DM follow-up",sub:"Day 9 of 14-day lifecycle.",nn:["DoorDash + calisthenics", "One creative + one business deliverable", "2hr focus / 20min walk rhythm"],dropLabel:"Days to JSS",dropDate:"2026-09-05"},
  "2026-08-25": {arc:"3",phase:"Worth It Post-Release",weekName:"Wk 20 — Worth It Live",dayLabel:"DATA PULL",badge:"Data",badgeClass:"badge-blue",cardClass:"card-left",deliverable:"Worth It 3-day save rate check · Catalog note",sub:"Day 10 of 14-day lifecycle.",nn:["DoorDash + calisthenics", "One creative + one business deliverable", "2hr focus / 20min walk rhythm"],dropLabel:"Days to JSS",dropDate:"2026-09-05"},
  "2026-08-26": {arc:"3",phase:"Worth It Post-Release",weekName:"Wk 20 — Worth It Live",dayLabel:"COMPOUND + MEME",badge:"Sustain",badgeClass:"badge-gold",cardClass:"card-left",deliverable:"Meme account compound posts · Sync pitch outreach",sub:"Day 11 of 14-day lifecycle.",nn:["DoorDash + calisthenics", "One creative + one business deliverable", "2hr focus / 20min walk rhythm"],dropLabel:"Days to JSS",dropDate:"2026-09-05"},
  "2026-08-27": {arc:"3",phase:"Worth It Post-Release",weekName:"Wk 20 — Worth It Live",dayLabel:"COMPLIANCE",badge:"Compliance",badgeClass:"badge-purple",cardClass:"card-left",deliverable:"Worth It compliance: ASCAP, MLC, Songtrust, Musixmatch",sub:"Day 12 of 14-day lifecycle.",nn:["DoorDash + calisthenics", "One creative + one business deliverable", "2hr focus / 20min walk rhythm"],dropLabel:"Days to JSS",dropDate:"2026-09-05"},
  "2026-08-28": {arc:"3",phase:"Worth It Post-Release",weekName:"Wk 20 — Worth It Live",dayLabel:"COMPOUND + CREAM PREP",badge:"Sustain",badgeClass:"badge-gold",cardClass:"card-left",deliverable:"Compound: playlist outreach · Sync pitching",sub:"Day 13 of 14-day lifecycle.",nn:["DoorDash + calisthenics", "One creative + one business deliverable", "2hr focus / 20min walk rhythm"],dropLabel:"Days to JSS",dropDate:"2026-09-05"},
  "2026-08-29": {arc:"3",phase:"Worth It Post-Release",weekName:"Wk 20 — Worth It Live",dayLabel:"COMPOUND + CREAM PREP",badge:"Sustain",badgeClass:"badge-gold",cardClass:"card-left",deliverable:"Compound: playlist outreach · Sync pitching",sub:"Day 14 of 14-day lifecycle.",nn:["DoorDash + calisthenics", "One creative + one business deliverable", "2hr focus / 20min walk rhythm"],dropLabel:"Days to JSS",dropDate:"2026-09-05"},
  // ═══ JUST SAY SO LIFECYCLE ═══
  "2026-08-30": {arc:"3",phase:"Just Say So Campaign",weekName:"Wk 21 — Just Say So Pre-Release",dayLabel:"SUNDAY — PRE-RELEASE REST",badge:"Sunday",badgeClass:"badge-purple",cardClass:"card-left",deliverable:"Grief journal · Just Say So pre-release check · Rest",sub:"T-6 to release.",nn:["Calisthenics — even if pointless", "Meditation / mudras — keep the slot", "One content piece max (ceiling, not floor)"],dropLabel:"Days to RCN",dropDate:"2026-09-19"},
  "2026-08-31": {arc:"3",phase:"Just Say So Campaign",weekName:"Wk 21 — Just Say So Pre-Release",dayLabel:"CONTENT SPRINT",badge:"Content",badgeClass:"badge-gold",cardClass:"card-left",deliverable:"World-building content · Meme posts",sub:"T-5 to release.",nn:["DoorDash + calisthenics", "One creative + one business deliverable", "2hr focus / 20min walk rhythm"],dropLabel:"Days to RCN",dropDate:"2026-09-19"},
  "2026-09-01": {arc:"3",phase:"Just Say So Campaign",weekName:"Wk 21 — Just Say So Pre-Release",dayLabel:"CONTENT + DM PREP",badge:"Content",badgeClass:"badge-gold",cardClass:"card-left",deliverable:"Surgical DM prep (sync sups + curators only)",sub:"T-4 to release.",nn:["DoorDash + calisthenics", "One creative + one business deliverable", "2hr focus / 20min walk rhythm"],dropLabel:"Days to RCN",dropDate:"2026-09-19"},
  "2026-09-02": {arc:"3",phase:"Just Say So Campaign",weekName:"Wk 21 — Just Say So Pre-Release",dayLabel:"EDITORIAL PITCH",badge:"Pitch",badgeClass:"badge-blue",cardClass:"card-left",deliverable:"Spotify editorial pitch · Teaser post",sub:"T-3 to release.",nn:["DoorDash + calisthenics", "One creative + one business deliverable", "2hr focus / 20min walk rhythm"],dropLabel:"Days to RCN",dropDate:"2026-09-19"},
  "2026-09-03": {arc:"3",phase:"Just Say So Campaign",weekName:"Wk 21 — Just Say So Pre-Release",dayLabel:"EVE OF RELEASE",badge:"Eve",badgeClass:"badge-orange",cardClass:"card-left",deliverable:"Final pre-save push · Everything staged for tomorrow",sub:"T-2 to release.",nn:["DoorDash + calisthenics", "One creative + one business deliverable", "2hr focus / 20min walk rhythm"],dropLabel:"Days to RCN",dropDate:"2026-09-19"},
  "2026-09-04": {arc:"3",phase:"Just Say So Campaign",weekName:"Wk 21 — Just Say So Pre-Release",dayLabel:"EVE OF JUST SAY SO",badge:"Eve",badgeClass:"badge-orange",cardClass:"card-left",deliverable:"Final pre-save push for Just Say So · DM list finalized · Ads staged",sub:"T-1 to release. Tomorrow Just Say So drops.",nn:["DoorDash + calisthenics", "One creative + one business deliverable", "2hr focus / 20min walk rhythm"],dropLabel:"Days to RCN",dropDate:"2026-09-19"},
  "2026-09-05": {arc:"3",phase:"Just Say So Release Day",weekName:"Wk 22 — Just Say So Drops",dayLabel:"JUST SAY SO DROPS",badge:"Release",badgeClass:"badge-red",cardClass:"card-left red",deliverable:"Just Say So live · Meme account drops 3-5 LYRC edits · Surgical DMs",sub:"Vault single 4 of 5. Release Radar trigger.",warning:{type:"important",icon:"🎉",text:"<strong>Just Say So is live.</strong> Vault 4 of 5."},nn:["Surgical DMs only","Meme: 3-5 LYRC edits","No stats after 8 PM"],dropLabel:"Days to RCN",dropDate:"2026-09-19"},
  "2026-09-06": {arc:"3",phase:"Just Say So Post-Release",weekName:"Wk 22 — Just Say So Live",dayLabel:"SUNDAY REVIEW",badge:"Sunday",badgeClass:"badge-purple",cardClass:"card-left",deliverable:"Grief journal · Just Say So week-1 data · Rest",sub:"Day 8 of 14-day lifecycle.",nn:["Calisthenics — even if pointless", "Meditation / mudras — keep the slot", "One content piece max (ceiling, not floor)"],dropLabel:"Days to RCN",dropDate:"2026-09-19"},
  "2026-09-07": {arc:"3",phase:"Just Say So Post-Release",weekName:"Wk 22 — Just Say So Live",dayLabel:"DM FOLLOW-UP + DATA",badge:"Data",badgeClass:"badge-blue",cardClass:"card-left",deliverable:"Just Say So 48-hr data · DM follow-up",sub:"Day 9 of 14-day lifecycle.",nn:["DoorDash + calisthenics", "One creative + one business deliverable", "2hr focus / 20min walk rhythm"],dropLabel:"Days to RCN",dropDate:"2026-09-19"},
  "2026-09-08": {arc:"3",phase:"Just Say So Post-Release",weekName:"Wk 22 — Just Say So Live",dayLabel:"DATA PULL",badge:"Data",badgeClass:"badge-blue",cardClass:"card-left",deliverable:"Just Say So 3-day save rate check · Catalog note",sub:"Day 10 of 14-day lifecycle.",nn:["DoorDash + calisthenics", "One creative + one business deliverable", "2hr focus / 20min walk rhythm"],dropLabel:"Days to RCN",dropDate:"2026-09-19"},
  "2026-09-09": {arc:"3",phase:"Just Say So Post-Release",weekName:"Wk 22 — Just Say So Live",dayLabel:"COMPOUND + MEME",badge:"Sustain",badgeClass:"badge-gold",cardClass:"card-left",deliverable:"Meme account compound posts · Sync pitch outreach",sub:"Day 11 of 14-day lifecycle.",nn:["DoorDash + calisthenics", "One creative + one business deliverable", "2hr focus / 20min walk rhythm"],dropLabel:"Days to RCN",dropDate:"2026-09-19"},
  "2026-09-10": {arc:"3",phase:"Just Say So Post-Release",weekName:"Wk 22 — Just Say So Live",dayLabel:"COMPLIANCE",badge:"Compliance",badgeClass:"badge-purple",cardClass:"card-left",deliverable:"Just Say So compliance: ASCAP, MLC, Songtrust, Musixmatch",sub:"Day 12 of 14-day lifecycle.",nn:["DoorDash + calisthenics", "One creative + one business deliverable", "2hr focus / 20min walk rhythm"],dropLabel:"Days to RCN",dropDate:"2026-09-19"},
  "2026-09-11": {arc:"3",phase:"Just Say So Post-Release",weekName:"Wk 22 — Just Say So Live",dayLabel:"COMPOUND + CREAM PREP",badge:"Sustain",badgeClass:"badge-gold",cardClass:"card-left",deliverable:"Compound: playlist outreach · Sync pitching",sub:"Day 13 of 14-day lifecycle.",nn:["DoorDash + calisthenics", "One creative + one business deliverable", "2hr focus / 20min walk rhythm"],dropLabel:"Days to RCN",dropDate:"2026-09-19"},
  "2026-09-12": {arc:"3",phase:"Just Say So Post-Release",weekName:"Wk 22 — Just Say So Live",dayLabel:"COMPOUND + CREAM PREP",badge:"Sustain",badgeClass:"badge-gold",cardClass:"card-left",deliverable:"Compound: playlist outreach · Sync pitching",sub:"Day 14 of 14-day lifecycle.",nn:["DoorDash + calisthenics", "One creative + one business deliverable", "2hr focus / 20min walk rhythm"],dropLabel:"Days to RCN",dropDate:"2026-09-19"},
  // ═══ RECONNECT LIFECYCLE ═══
  "2026-09-13": {arc:"3",phase:"Reconnect Campaign",weekName:"Wk 23 — Reconnect Pre-Release",dayLabel:"SUNDAY — PRE-RELEASE REST",badge:"Sunday",badgeClass:"badge-purple",cardClass:"card-left",deliverable:"Grief journal · Reconnect pre-release check · Rest",sub:"T-6 to release.",nn:["Calisthenics — even if pointless", "Meditation / mudras — keep the slot", "One content piece max (ceiling, not floor)"],dropLabel:"Days to CREAM",dropDate:"2026-10-23"},
  "2026-09-14": {arc:"3",phase:"Reconnect Campaign",weekName:"Wk 23 — Reconnect Pre-Release",dayLabel:"CONTENT SPRINT",badge:"Content",badgeClass:"badge-gold",cardClass:"card-left",deliverable:"World-building content · Meme posts",sub:"T-5 to release.",nn:["DoorDash + calisthenics", "One creative + one business deliverable", "2hr focus / 20min walk rhythm"],dropLabel:"Days to CREAM",dropDate:"2026-10-23"},
  "2026-09-15": {arc:"3",phase:"Reconnect Campaign",weekName:"Wk 23 — Reconnect Pre-Release",dayLabel:"CONTENT + DM PREP",badge:"Content",badgeClass:"badge-gold",cardClass:"card-left",deliverable:"Surgical DM prep (sync sups + curators only)",sub:"T-4 to release.",nn:["DoorDash + calisthenics", "One creative + one business deliverable", "2hr focus / 20min walk rhythm"],dropLabel:"Days to CREAM",dropDate:"2026-10-23"},
  "2026-09-16": {arc:"3",phase:"Reconnect Campaign",weekName:"Wk 23 — Reconnect Pre-Release",dayLabel:"EDITORIAL PITCH",badge:"Pitch",badgeClass:"badge-blue",cardClass:"card-left",deliverable:"Spotify editorial pitch · Teaser post",sub:"T-3 to release.",nn:["DoorDash + calisthenics", "One creative + one business deliverable", "2hr focus / 20min walk rhythm"],dropLabel:"Days to CREAM",dropDate:"2026-10-23"},
  "2026-09-17": {arc:"3",phase:"Reconnect Campaign",weekName:"Wk 23 — Reconnect Pre-Release",dayLabel:"EVE OF RELEASE",badge:"Eve",badgeClass:"badge-orange",cardClass:"card-left",deliverable:"Final pre-save push · Everything staged for tomorrow",sub:"T-2 to release.",nn:["DoorDash + calisthenics", "One creative + one business deliverable", "2hr focus / 20min walk rhythm"],dropLabel:"Days to CREAM",dropDate:"2026-10-23"},
  "2026-09-18": {arc:"3",phase:"Reconnect Campaign",weekName:"Wk 23 — Reconnect Pre-Release",dayLabel:"EVE OF RECONNECT",badge:"Eve",badgeClass:"badge-orange",cardClass:"card-left",deliverable:"Final pre-save push for Reconnect · DM list finalized · Ads staged",sub:"T-1 to release. Tomorrow Reconnect drops.",nn:["DoorDash + calisthenics", "One creative + one business deliverable", "2hr focus / 20min walk rhythm"],dropLabel:"Days to CREAM",dropDate:"2026-10-23"},
  "2026-09-19": {arc:"3",phase:"Reconnect Release Day",weekName:"Wk 24 — Reconnect Drops",dayLabel:"RECONNECT DROPS",badge:"Release",badgeClass:"badge-red",cardClass:"card-left red",deliverable:"Reconnect live · Meme account drops 3-5 LYRC edits · Surgical DMs",sub:"Vault single 5 of 5. Release Radar trigger.",warning:{type:"important",icon:"🎉",text:"<strong>Reconnect is live.</strong> Vault 5 of 5."},nn:["Surgical DMs only","Meme: 3-5 LYRC edits","No stats after 8 PM"],dropLabel:"Days to CREAM",dropDate:"2026-10-23"},
  "2026-09-20": {arc:"3",phase:"Reconnect Post-Release",weekName:"Wk 24 — Reconnect Live",dayLabel:"SUNDAY REVIEW",badge:"Sunday",badgeClass:"badge-purple",cardClass:"card-left",deliverable:"Grief journal · Reconnect week-1 data · Rest · 180-day horizon check",sub:"Day 8 of 14-day lifecycle.",nn:["Calisthenics — even if pointless", "Meditation / mudras — keep the slot", "One content piece max (ceiling, not floor)"],dropLabel:"Days to CREAM",dropDate:"2026-10-23"},
  "2026-09-21": {arc:"3",phase:"Reconnect Post-Release",weekName:"Wk 24 — Reconnect Live",dayLabel:"DM FOLLOW-UP + DATA",badge:"Data",badgeClass:"badge-blue",cardClass:"card-left",deliverable:"Reconnect 48-hr data · DM follow-up",sub:"Day 9 of 14-day lifecycle.",nn:["DoorDash + calisthenics", "One creative + one business deliverable", "2hr focus / 20min walk rhythm"],dropLabel:"Days to CREAM",dropDate:"2026-10-23"},
  "2026-09-22": {arc:"3",phase:"Reconnect Post-Release",weekName:"Wk 24 — Reconnect Live",dayLabel:"DATA PULL",badge:"Data",badgeClass:"badge-blue",cardClass:"card-left",deliverable:"Reconnect 3-day save rate check · Catalog note",sub:"Day 10 of 14-day lifecycle.",nn:["DoorDash + calisthenics", "One creative + one business deliverable", "2hr focus / 20min walk rhythm"],dropLabel:"Days to CREAM",dropDate:"2026-10-23"},
  "2026-09-23": {arc:"3",phase:"Reconnect Post-Release",weekName:"Wk 24 — Reconnect Live",dayLabel:"COMPOUND + MEME",badge:"Sustain",badgeClass:"badge-gold",cardClass:"card-left",deliverable:"Meme account compound posts · Sync pitch outreach",sub:"Day 11 of 14-day lifecycle.",nn:["DoorDash + calisthenics", "One creative + one business deliverable", "2hr focus / 20min walk rhythm"],dropLabel:"Days to CREAM",dropDate:"2026-10-23"},
  "2026-09-24": {arc:"3",phase:"Reconnect Post-Release",weekName:"Wk 24 — Reconnect Live",dayLabel:"COMPLIANCE",badge:"Compliance",badgeClass:"badge-purple",cardClass:"card-left",deliverable:"Reconnect compliance: ASCAP, MLC, Songtrust, Musixmatch · CREAM pre-prod sequencing if GO",sub:"Day 12 of 14-day lifecycle.",nn:["DoorDash + calisthenics", "One creative + one business deliverable", "2hr focus / 20min walk rhythm"],dropLabel:"Days to CREAM",dropDate:"2026-10-23"},
  "2026-09-25": {arc:"3",phase:"Reconnect Post-Release",weekName:"Wk 24 — Reconnect Live",dayLabel:"COMPOUND + CREAM PREP",badge:"Sustain",badgeClass:"badge-gold",cardClass:"card-left",deliverable:"Compound: playlist outreach · Sync pitching · Full catalog audit · Plan Oct-Dec",sub:"Day 13 of 14-day lifecycle.",nn:["DoorDash + calisthenics", "One creative + one business deliverable", "2hr focus / 20min walk rhythm"],dropLabel:"Days to CREAM",dropDate:"2026-10-23"},
  "2026-09-26": {arc:"3",phase:"Reconnect Post-Release",weekName:"Wk 24 — Reconnect Live",dayLabel:"COMPOUND + CREAM PREP",badge:"Sustain",badgeClass:"badge-gold",cardClass:"card-left",deliverable:"Compound: playlist outreach · Sync pitching · Full catalog audit · Plan Oct-Dec",sub:"Day 14 of 14-day lifecycle.",nn:["DoorDash + calisthenics", "One creative + one business deliverable", "2hr focus / 20min walk rhythm"],dropLabel:"Days to CREAM",dropDate:"2026-10-23"},
};

export const VOCAL_PRINCIPLES: string[] = [
  '<strong>"You can\'t edit emotion."</strong> If the take has the story, take it even if pitch isn\'t perfect. Over-tuning strips the natural inflections that make a vocal human.',
  '<strong>Environment before artist.</strong> Lighting, temp, headphone mix, line checks — all done before entering. Zero technical friction.',
  '<strong>Don\'t record first.</strong> Full run to assess before a single take. The first run shows range, sticky spots, preparedness.',
  '<strong>Start at the verse, not the chorus.</strong> Voice settles. Chorus on take 15 will be better.',
  '<strong>Click as reference, not ruler.</strong> Human feel is the point. Don\'t grid-lock.',
  '<strong>Writing session vocals are often the best takes.</strong> Caught in the moment — genuine, no self-consciousness. If you catch something real, that IS the vocal.',
  '<strong>For emotion: visceral memory.</strong> "What did it smell like? What did the room look like?" Unlocks genuine delivery.',
  '<strong>Don\'t take too much away.</strong> Whether tuning, comping, or layering — if it sounds better natural, leave it. The artist\'s voice IS the art. Everything else serves that.',
];

// ═══ HELPER FUNCTIONS ═══

/** Get today's ISO date string in local time */
export function todayIsoDate(): string {
  const d = new Date();
  const y = d.getFullYear();
  const m = String(d.getMonth() + 1).padStart(2, "0");
  const day = String(d.getDate()).padStart(2, "0");
  return `${y}-${m}-${day}`;
}

/** Get today's phase data from the PHASE_MAP, or null if outside the 91-day window */
export function getTodayPlan(): PhaseDay | null {
  return PHASE_MAP[todayIsoDate()] ?? null;
}

/** Calculate sovereignty days since April 17, 2026 */
export function getSovereigntyDays(): number {
  const sovStart = new Date("2026-04-17T00:00:00");
  const now = new Date();
  return Math.max(1, Math.floor((now.getTime() - sovStart.getTime()) / (1000 * 60 * 60 * 24)));
}

/** Calculate days to a target date */
export function daysTo(targetDate: string): number {
  const target = new Date(targetDate + "T00:00:00");
  const now = new Date();
  return Math.ceil((target.getTime() - now.getTime()) / (1000 * 60 * 60 * 24));
}
